// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: admin.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountDownloads = `-- name: AdminCountDownloads :one
SELECT COUNT(*) FROM downloads d
JOIN users u ON u.id = d.user_id
WHERE d.deleted_at IS NULL
  AND ($1::uuid IS NULL OR d.user_id = $1::uuid)
  AND ($2::core.download_status IS NULL OR d.status = $2::core.download_status)
  AND (
    $3::text IS NULL
    OR lower(d.title) LIKE '%' || lower($3::text) || '%'
    OR lower(u.email) LIKE '%' || lower($3::text) || '%'
  )
`

type AdminCountDownloadsParams struct {
	UserID pgtype.UUID            `json:"user_id"`
	Status NullCoreDownloadStatus `json:"status"`
	Search pgtype.Text            `json:"search"`
}

func (q *Queries) AdminCountDownloads(ctx context.Context, arg AdminCountDownloadsParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountDownloads, arg.UserID, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountSuperAdmins = `-- name: AdminCountSuperAdmins :one
SELECT COUNT(*) FROM users
WHERE role = 'super_admin'
  AND active = true
  AND deleted_at IS NULL
`

func (q *Queries) AdminCountSuperAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountSuperAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountUsers = `-- name: AdminCountUsers :one
SELECT COUNT(*) FROM users u
WHERE u.deleted_at IS NULL
  -- Contas de SERVIÇO ficam fora: elas são gerenciadas pela seção de
  -- integrações, e não por esta tela. Listá-las aqui ofereceria ao
  -- administrador botões que não valem para elas (redefinir senha,
  -- promover a admin) e misturaria sistemas com pessoas na contagem.
  AND u.kind = 'human'
  AND (
    $1::text IS NULL
    OR lower(u.full_name) LIKE '%' || lower($1::text) || '%'
    OR lower(u.email) LIKE '%' || lower($1::text) || '%'
  )
  AND ($2::core.plan_type IS NULL OR u.plan = $2::core.plan_type)
  AND ($3::core.user_role IS NULL OR u.role = $3::core.user_role)
  AND ($4::boolean IS NULL OR u.active = $4::boolean)
`

type AdminCountUsersParams struct {
	Search pgtype.Text      `json:"search"`
	Plan   NullCorePlanType `json:"plan"`
	Role   NullCoreUserRole `json:"role"`
	Active pgtype.Bool      `json:"active"`
}

func (q *Queries) AdminCountUsers(ctx context.Context, arg AdminCountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountUsers,
		arg.Search,
		arg.Plan,
		arg.Role,
		arg.Active,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminDownloadsByFormat = `-- name: AdminDownloadsByFormat :many
SELECT
  format,
  COUNT(*)::bigint AS total,
  COALESCE(SUM(file_size_bytes), 0)::bigint AS transferred_bytes
FROM downloads
WHERE deleted_at IS NULL
  AND created_at >= $1
  AND created_at < $2
GROUP BY format
ORDER BY total DESC
`

type AdminDownloadsByFormatParams struct {
	From *time.Time `json:"from"`
	To   *time.Time `json:"to"`
}

type AdminDownloadsByFormatRow struct {
	Format           CoreFormatType `json:"format"`
	Total            int64          `json:"total"`
	TransferredBytes int64          `json:"transferred_bytes"`
}

func (q *Queries) AdminDownloadsByFormat(ctx context.Context, arg AdminDownloadsByFormatParams) ([]AdminDownloadsByFormatRow, error) {
	rows, err := q.db.Query(ctx, adminDownloadsByFormat, arg.From, arg.To)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminDownloadsByFormatRow{}
	for rows.Next() {
		var i AdminDownloadsByFormatRow
		if err := rows.Scan(&i.Format, &i.Total, &i.TransferredBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminDownloadsSummary = `-- name: AdminDownloadsSummary :one

SELECT
  COUNT(*)::bigint AS total,
  COUNT(*) FILTER (WHERE status = 'COMPLETED')::bigint AS completed,
  COUNT(*) FILTER (WHERE status = 'FAILED')::bigint AS failed,
  COUNT(*) FILTER (WHERE status IN ('PENDING', 'PROCESSING', 'RETRYING'))::bigint AS processing,
  COUNT(*) FILTER (WHERE status = 'EXPIRED')::bigint AS expired,
  COUNT(DISTINCT user_id)::bigint AS active_users,
  COALESCE(SUM(file_size_bytes), 0)::bigint AS transferred_bytes
FROM downloads
WHERE deleted_at IS NULL
  AND created_at >= $1
  AND created_at < $2
`

type AdminDownloadsSummaryParams struct {
	From *time.Time `json:"from"`
	To   *time.Time `json:"to"`
}

type AdminDownloadsSummaryRow struct {
	Total            int64 `json:"total"`
	Completed        int64 `json:"completed"`
	Failed           int64 `json:"failed"`
	Processing       int64 `json:"processing"`
	Expired          int64 `json:"expired"`
	ActiveUsers      int64 `json:"active_users"`
	TransferredBytes int64 `json:"transferred_bytes"`
}

// ---------------------------------------------------------------------------
// Métricas
// ---------------------------------------------------------------------------
// Números do período escolhido. Um único SELECT em vez de seis: o painel abre
// com todos eles na tela ao mesmo tempo.
func (q *Queries) AdminDownloadsSummary(ctx context.Context, arg AdminDownloadsSummaryParams) (AdminDownloadsSummaryRow, error) {
	row := q.db.QueryRow(ctx, adminDownloadsSummary, arg.From, arg.To)
	var i AdminDownloadsSummaryRow
	err := row.Scan(
		&i.Total,
		&i.Completed,
		&i.Failed,
		&i.Processing,
		&i.Expired,
		&i.ActiveUsers,
		&i.TransferredBytes,
	)
	return i, err
}

const adminDownloadsTimeSeries = `-- name: AdminDownloadsTimeSeries :many
SELECT
  b.inicio::timestamptz AS bucket,
  COALESCE(COUNT(d.id), 0)::bigint AS total,
  COALESCE(COUNT(d.id) FILTER (WHERE d.status = 'COMPLETED'), 0)::bigint AS completed,
  COALESCE(COUNT(d.id) FILTER (WHERE d.status = 'FAILED'), 0)::bigint AS failed,
  COALESCE(SUM(d.file_size_bytes), 0)::bigint AS transferred_bytes
FROM (
  SELECT
    periodo AT TIME ZONE 'America/Sao_Paulo' AS inicio,
    (periodo + ('1 ' || $1::text)::interval)
      AT TIME ZONE 'America/Sao_Paulo' AS fim
  FROM generate_series(
    date_trunc(
      $1::text,
      $2::timestamptz AT TIME ZONE 'America/Sao_Paulo'
    ),
    -- O limite superior é o último balde que COMEÇA dentro do período. Sem o
    -- recuo, generate_series devolveria um balde extra começando exatamente no
    -- fim do intervalo, e o gráfico exibiria uma coluna de um dia que ainda não
    -- aconteceu.
    date_trunc(
      $1::text,
      ($3::timestamptz - INTERVAL '1 microsecond') AT TIME ZONE 'America/Sao_Paulo'
    ),
    ('1 ' || $1::text)::interval
  ) AS periodo
) b
LEFT JOIN downloads d
  ON d.deleted_at IS NULL
  AND d.created_at >= b.inicio
  AND d.created_at < b.fim
  -- Semana e mês truncam para trás, então o primeiro balde pode começar antes
  -- do período pedido. Sem estes dois limites ele somaria downloads anteriores
  -- ao intervalo, e a primeira barra apareceria inflada.
  AND d.created_at >= $2::timestamptz
  AND d.created_at < $3::timestamptz
GROUP BY b.inicio
ORDER BY b.inicio
`

type AdminDownloadsTimeSeriesParams struct {
	Granularity string     `json:"granularity"`
	From        *time.Time `json:"from"`
	To          *time.Time `json:"to"`
}

type AdminDownloadsTimeSeriesRow struct {
	Bucket           *time.Time `json:"bucket"`
	Total            int64      `json:"total"`
	Completed        int64      `json:"completed"`
	Failed           int64      `json:"failed"`
	TransferredBytes int64      `json:"transferred_bytes"`
}

// Série temporal do gráfico. generate_series preenche os períodos sem download
// com zero: sem isso o gráfico une dois pontos distantes com uma reta e inventa
// movimento que não existiu.
//
// Os baldes são truncados NO FUSO DE SÃO PAULO, e não em UTC. É o mesmo corte
// usado pelo limite diário; em UTC, o "dia" do gráfico começaria às 21h do dia
// anterior e não bateria com o contador que o usuário vê.
func (q *Queries) AdminDownloadsTimeSeries(ctx context.Context, arg AdminDownloadsTimeSeriesParams) ([]AdminDownloadsTimeSeriesRow, error) {
	rows, err := q.db.Query(ctx, adminDownloadsTimeSeries, arg.Granularity, arg.From, arg.To)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminDownloadsTimeSeriesRow{}
	for rows.Next() {
		var i AdminDownloadsTimeSeriesRow
		if err := rows.Scan(
			&i.Bucket,
			&i.Total,
			&i.Completed,
			&i.Failed,
			&i.TransferredBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetUserDetail = `-- name: AdminGetUserDetail :one
SELECT
  u.id, u.full_name, u.photo_url, u.email, u.hashed_password, u.password_changed_at, u.active, u.plan, u.daily_limit, u.last_login, u.is_verified, u.created_at, u.updated_at, u.role, u.deleted_at, u.kind,
  COUNT(d.id) FILTER (WHERE d.deleted_at IS NULL)::bigint AS downloads_total,
  COUNT(d.id) FILTER (WHERE d.deleted_at IS NULL AND d.status = 'COMPLETED')::bigint AS downloads_completed,
  COUNT(d.id) FILTER (WHERE d.deleted_at IS NULL AND d.status = 'FAILED')::bigint AS downloads_failed,
  COALESCE(SUM(d.file_size_bytes) FILTER (
    WHERE d.deleted_at IS NULL AND d.status = 'COMPLETED'
  ), 0)::bigint AS storage_bytes,
  COALESCE(SUM(d.file_size_bytes) FILTER (WHERE d.deleted_at IS NULL), 0)::bigint AS transferred_bytes
FROM users u
LEFT JOIN downloads d ON d.user_id = u.id
WHERE u.id = $1
  AND u.deleted_at IS NULL
GROUP BY u.id
`

type AdminGetUserDetailRow struct {
	ID                 uuid.UUID          `json:"id"`
	FullName           string             `json:"full_name"`
	PhotoUrl           pgtype.Text        `json:"photo_url"`
	Email              string             `json:"email"`
	HashedPassword     string             `json:"hashed_password"`
	PasswordChangedAt  *time.Time         `json:"password_changed_at"`
	Active             bool               `json:"active"`
	Plan               CorePlanType       `json:"plan"`
	DailyLimit         int32              `json:"daily_limit"`
	LastLogin          pgtype.Timestamptz `json:"last_login"`
	IsVerified         bool               `json:"is_verified"`
	CreatedAt          *time.Time         `json:"created_at"`
	UpdatedAt          *time.Time         `json:"updated_at"`
	Role               CoreUserRole       `json:"role"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	Kind               CoreUserKind       `json:"kind"`
	DownloadsTotal     int64              `json:"downloads_total"`
	DownloadsCompleted int64              `json:"downloads_completed"`
	DownloadsFailed    int64              `json:"downloads_failed"`
	StorageBytes       int64              `json:"storage_bytes"`
	TransferredBytes   int64              `json:"transferred_bytes"`
}

func (q *Queries) AdminGetUserDetail(ctx context.Context, id uuid.UUID) (AdminGetUserDetailRow, error) {
	row := q.db.QueryRow(ctx, adminGetUserDetail, id)
	var i AdminGetUserDetailRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.PhotoUrl,
		&i.Email,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.Active,
		&i.Plan,
		&i.DailyLimit,
		&i.LastLogin,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.DeletedAt,
		&i.Kind,
		&i.DownloadsTotal,
		&i.DownloadsCompleted,
		&i.DownloadsFailed,
		&i.StorageBytes,
		&i.TransferredBytes,
	)
	return i, err
}

const adminListDownloads = `-- name: AdminListDownloads :many

SELECT
  d.id, d.user_id, d.original_url, d.title, d.format, d.status, d.thumbnail_url, d.file_url, d.expires_at, d.duration_seconds, d.error_message, d.created_at, d.deleted_at, d.file_size_bytes, d.platform, d.provider, d.format_id, d.quality_label, d.progress_percent, d.downloaded_bytes, d.total_bytes, d.speed_bps, d.eta_seconds, d.started_at, d.finished_at, d.uploader, d.format_height, d.error_detail,
  u.full_name AS user_name,
  u.email AS user_email
FROM downloads d
JOIN users u ON u.id = d.user_id
WHERE d.deleted_at IS NULL
  AND ($3::uuid IS NULL OR d.user_id = $3::uuid)
  AND ($4::core.download_status IS NULL OR d.status = $4::core.download_status)
  AND (
    $5::text IS NULL
    OR lower(d.title) LIKE '%' || lower($5::text) || '%'
    OR lower(u.email) LIKE '%' || lower($5::text) || '%'
  )
ORDER BY d.created_at DESC
LIMIT $1 OFFSET $2
`

type AdminListDownloadsParams struct {
	Limit  int32                  `json:"limit"`
	Offset int32                  `json:"offset"`
	UserID pgtype.UUID            `json:"user_id"`
	Status NullCoreDownloadStatus `json:"status"`
	Search pgtype.Text            `json:"search"`
}

type AdminListDownloadsRow struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	OriginalUrl     string             `json:"original_url"`
	Title           string             `json:"title"`
	Format          CoreFormatType     `json:"format"`
	Status          CoreDownloadStatus `json:"status"`
	ThumbnailUrl    pgtype.Text        `json:"thumbnail_url"`
	FileUrl         pgtype.Text        `json:"file_url"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	DurationSeconds pgtype.Int4        `json:"duration_seconds"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	CreatedAt       *time.Time         `json:"created_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	FileSizeBytes   int64              `json:"file_size_bytes"`
	Platform        string             `json:"platform"`
	Provider        pgtype.Text        `json:"provider"`
	FormatID        pgtype.Text        `json:"format_id"`
	QualityLabel    pgtype.Text        `json:"quality_label"`
	ProgressPercent pgtype.Numeric     `json:"progress_percent"`
	DownloadedBytes int64              `json:"downloaded_bytes"`
	TotalBytes      int64              `json:"total_bytes"`
	SpeedBps        int64              `json:"speed_bps"`
	EtaSeconds      int32              `json:"eta_seconds"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
	Uploader        pgtype.Text        `json:"uploader"`
	FormatHeight    int32              `json:"format_height"`
	ErrorDetail     pgtype.Text        `json:"error_detail"`
	UserName        string             `json:"user_name"`
	UserEmail       string             `json:"user_email"`
}

// ---------------------------------------------------------------------------
// Downloads
// ---------------------------------------------------------------------------
func (q *Queries) AdminListDownloads(ctx context.Context, arg AdminListDownloadsParams) ([]AdminListDownloadsRow, error) {
	rows, err := q.db.Query(ctx, adminListDownloads,
		arg.Limit,
		arg.Offset,
		arg.UserID,
		arg.Status,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListDownloadsRow{}
	for rows.Next() {
		var i AdminListDownloadsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OriginalUrl,
			&i.Title,
			&i.Format,
			&i.Status,
			&i.ThumbnailUrl,
			&i.FileUrl,
			&i.ExpiresAt,
			&i.DurationSeconds,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.FileSizeBytes,
			&i.Platform,
			&i.Provider,
			&i.FormatID,
			&i.QualityLabel,
			&i.ProgressPercent,
			&i.DownloadedBytes,
			&i.TotalBytes,
			&i.SpeedBps,
			&i.EtaSeconds,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Uploader,
			&i.FormatHeight,
			&i.ErrorDetail,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUsers = `-- name: AdminListUsers :many


SELECT
  u.id, u.full_name, u.photo_url, u.email, u.hashed_password, u.password_changed_at, u.active, u.plan, u.daily_limit, u.last_login, u.is_verified, u.created_at, u.updated_at, u.role, u.deleted_at, u.kind,
  COUNT(d.id) FILTER (WHERE d.deleted_at IS NULL)::bigint AS downloads_total,
  COALESCE(SUM(d.file_size_bytes) FILTER (
    WHERE d.deleted_at IS NULL AND d.status = 'COMPLETED'
  ), 0)::bigint AS storage_bytes
FROM users u
LEFT JOIN downloads d ON d.user_id = u.id
WHERE u.deleted_at IS NULL
  -- Contas de SERVIÇO ficam fora: elas são gerenciadas pela seção de
  -- integrações, e não por esta tela. Listá-las aqui ofereceria ao
  -- administrador botões que não valem para elas (redefinir senha,
  -- promover a admin) e misturaria sistemas com pessoas na contagem.
  AND u.kind = 'human'
  AND (
    $3::text IS NULL
    OR lower(u.full_name) LIKE '%' || lower($3::text) || '%'
    OR lower(u.email) LIKE '%' || lower($3::text) || '%'
  )
  AND ($4::core.plan_type IS NULL OR u.plan = $4::core.plan_type)
  AND ($5::core.user_role IS NULL OR u.role = $5::core.user_role)
  AND ($6::boolean IS NULL OR u.active = $6::boolean)
GROUP BY u.id
ORDER BY u.created_at DESC
LIMIT $1 OFFSET $2
`

type AdminListUsersParams struct {
	Limit  int32            `json:"limit"`
	Offset int32            `json:"offset"`
	Search pgtype.Text      `json:"search"`
	Plan   NullCorePlanType `json:"plan"`
	Role   NullCoreUserRole `json:"role"`
	Active pgtype.Bool      `json:"active"`
}

type AdminListUsersRow struct {
	ID                uuid.UUID          `json:"id"`
	FullName          string             `json:"full_name"`
	PhotoUrl          pgtype.Text        `json:"photo_url"`
	Email             string             `json:"email"`
	HashedPassword    string             `json:"hashed_password"`
	PasswordChangedAt *time.Time         `json:"password_changed_at"`
	Active            bool               `json:"active"`
	Plan              CorePlanType       `json:"plan"`
	DailyLimit        int32              `json:"daily_limit"`
	LastLogin         pgtype.Timestamptz `json:"last_login"`
	IsVerified        bool               `json:"is_verified"`
	CreatedAt         *time.Time         `json:"created_at"`
	UpdatedAt         *time.Time         `json:"updated_at"`
	Role              CoreUserRole       `json:"role"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	Kind              CoreUserKind       `json:"kind"`
	DownloadsTotal    int64              `json:"downloads_total"`
	StorageBytes      int64              `json:"storage_bytes"`
}

// Consultas exclusivas do painel de Super Admin.
//
// Todas ignoram registros removidos e, quando fazem contas de armazenamento,
// somam apenas o que ainda existe no bucket.
// ---------------------------------------------------------------------------
// Usuários
// ---------------------------------------------------------------------------
// Listagem paginada com busca por nome/e-mail e filtros opcionais. Os
// sqlc.narg vazios desativam o próprio filtro, o que evita uma consulta por
// combinação de filtros.
func (q *Queries) AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error) {
	rows, err := q.db.Query(ctx, adminListUsers,
		arg.Limit,
		arg.Offset,
		arg.Search,
		arg.Plan,
		arg.Role,
		arg.Active,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUsersRow{}
	for rows.Next() {
		var i AdminListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.PhotoUrl,
			&i.Email,
			&i.HashedPassword,
			&i.PasswordChangedAt,
			&i.Active,
			&i.Plan,
			&i.DailyLimit,
			&i.LastLogin,
			&i.IsVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.DeletedAt,
			&i.Kind,
			&i.DownloadsTotal,
			&i.StorageBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminPlatformTotals = `-- name: AdminPlatformTotals :one
SELECT
  (SELECT COUNT(*) FROM users WHERE deleted_at IS NULL)::bigint AS users_total,
  (SELECT COUNT(*) FROM users WHERE deleted_at IS NULL AND active = true)::bigint AS users_active,
  (SELECT COUNT(*) FROM users WHERE deleted_at IS NULL AND plan = 'premium')::bigint AS users_premium,
  (SELECT COUNT(*) FROM users WHERE deleted_at IS NULL AND created_at >= now() - INTERVAL '30 days')::bigint AS users_new_30d,
  (SELECT COUNT(*) FROM downloads WHERE deleted_at IS NULL)::bigint AS downloads_total
`

type AdminPlatformTotalsRow struct {
	UsersTotal     int64 `json:"users_total"`
	UsersActive    int64 `json:"users_active"`
	UsersPremium   int64 `json:"users_premium"`
	UsersNew30d    int64 `json:"users_new_30d"`
	DownloadsTotal int64 `json:"downloads_total"`
}

// Totais que não dependem do período escolhido.
func (q *Queries) AdminPlatformTotals(ctx context.Context) (AdminPlatformTotalsRow, error) {
	row := q.db.QueryRow(ctx, adminPlatformTotals)
	var i AdminPlatformTotalsRow
	err := row.Scan(
		&i.UsersTotal,
		&i.UsersActive,
		&i.UsersPremium,
		&i.UsersNew30d,
		&i.DownloadsTotal,
	)
	return i, err
}

const adminSoftDeleteUser = `-- name: AdminSoftDeleteUser :exec
UPDATE users
SET deleted_at = now(), active = false, updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

// Remoção lógica. O histórico de downloads é preservado de propósito: ele
// referencia users(id) e ainda responde pela contabilidade de armazenamento.
func (q *Queries) AdminSoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, adminSoftDeleteUser, id)
	return err
}

const adminStorageSummary = `-- name: AdminStorageSummary :one
SELECT
  COALESCE(SUM(file_size_bytes) FILTER (
    WHERE status = 'COMPLETED'
      AND deleted_at IS NULL
      AND (expires_at IS NULL OR expires_at > now())
  ), 0)::bigint AS stored_bytes,
  COUNT(*) FILTER (
    WHERE status = 'COMPLETED'
      AND deleted_at IS NULL
      AND (expires_at IS NULL OR expires_at > now())
  )::bigint AS stored_files,
  COALESCE(SUM(file_size_bytes), 0)::bigint AS lifetime_bytes,
  COALESCE(SUM(file_size_bytes) FILTER (
    WHERE status = 'EXPIRED' OR deleted_at IS NOT NULL
  ), 0)::bigint AS freed_bytes,
  COUNT(*) FILTER (WHERE status = 'EXPIRED' OR deleted_at IS NOT NULL)::bigint AS freed_files
FROM downloads
`

type AdminStorageSummaryRow struct {
	StoredBytes   int64 `json:"stored_bytes"`
	StoredFiles   int64 `json:"stored_files"`
	LifetimeBytes int64 `json:"lifetime_bytes"`
	FreedBytes    int64 `json:"freed_bytes"`
	FreedFiles    int64 `json:"freed_files"`
}

// Armazenamento. "Atual" é o que ainda ocupa espaço no bucket: concluído, não
// removido e dentro da validade. "Histórico" é tudo que já passou por lá.
func (q *Queries) AdminStorageSummary(ctx context.Context) (AdminStorageSummaryRow, error) {
	row := q.db.QueryRow(ctx, adminStorageSummary)
	var i AdminStorageSummaryRow
	err := row.Scan(
		&i.StoredBytes,
		&i.StoredFiles,
		&i.LifetimeBytes,
		&i.FreedBytes,
		&i.FreedFiles,
	)
	return i, err
}

const adminTopUsers = `-- name: AdminTopUsers :many
SELECT
  u.id,
  u.full_name,
  u.email,
  u.plan,
  COUNT(d.id)::bigint AS downloads_total,
  COALESCE(SUM(d.file_size_bytes), 0)::bigint AS transferred_bytes
FROM downloads d
JOIN users u ON u.id = d.user_id
WHERE d.deleted_at IS NULL
  AND u.deleted_at IS NULL
  AND d.created_at >= $2
  AND d.created_at < $3
GROUP BY u.id
ORDER BY downloads_total DESC
LIMIT $1
`

type AdminTopUsersParams struct {
	Limit int32      `json:"limit"`
	From  *time.Time `json:"from"`
	To    *time.Time `json:"to"`
}

type AdminTopUsersRow struct {
	ID               uuid.UUID    `json:"id"`
	FullName         string       `json:"full_name"`
	Email            string       `json:"email"`
	Plan             CorePlanType `json:"plan"`
	DownloadsTotal   int64        `json:"downloads_total"`
	TransferredBytes int64        `json:"transferred_bytes"`
}

func (q *Queries) AdminTopUsers(ctx context.Context, arg AdminTopUsersParams) ([]AdminTopUsersRow, error) {
	rows, err := q.db.Query(ctx, adminTopUsers, arg.Limit, arg.From, arg.To)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminTopUsersRow{}
	for rows.Next() {
		var i AdminTopUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.Plan,
			&i.DownloadsTotal,
			&i.TransferredBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUpdateUser = `-- name: AdminUpdateUser :one
UPDATE users
SET
  full_name = COALESCE($2, full_name),
  email = COALESCE($3, email),
  plan = COALESCE($4, plan),
  role = COALESCE($5, role),
  daily_limit = COALESCE($6, daily_limit),
  active = COALESCE($7, active),
  is_verified = COALESCE($8, is_verified),
  hashed_password = COALESCE($9, hashed_password),
  password_changed_at = COALESCE($10, password_changed_at),
  updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, full_name, photo_url, email, hashed_password, password_changed_at, active, plan, daily_limit, last_login, is_verified, created_at, updated_at, role, deleted_at, kind
`

type AdminUpdateUserParams struct {
	ID                uuid.UUID          `json:"id"`
	FullName          pgtype.Text        `json:"full_name"`
	Email             pgtype.Text        `json:"email"`
	Plan              NullCorePlanType   `json:"plan"`
	Role              NullCoreUserRole   `json:"role"`
	DailyLimit        pgtype.Int4        `json:"daily_limit"`
	Active            pgtype.Bool        `json:"active"`
	IsVerified        pgtype.Bool        `json:"is_verified"`
	HashedPassword    pgtype.Text        `json:"hashed_password"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
}

// Atualização vinda do painel. Diferente de UpdateUser, esta pode mexer no
// papel — e é por isso que ela é separada: a rota de perfil do usuário comum
// nunca deve conseguir se promover.
func (q *Queries) AdminUpdateUser(ctx context.Context, arg AdminUpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, adminUpdateUser,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.Plan,
		arg.Role,
		arg.DailyLimit,
		arg.Active,
		arg.IsVerified,
		arg.HashedPassword,
		arg.PasswordChangedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.PhotoUrl,
		&i.Email,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.Active,
		&i.Plan,
		&i.DailyLimit,
		&i.LastLogin,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.DeletedAt,
		&i.Kind,
	)
	return i, err
}
