// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: downloads.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelDownload = `-- name: CancelDownload :one
UPDATE downloads
SET status = CASE
      WHEN status IN ('PENDING', 'PROCESSING', 'RETRYING')
        THEN 'CANCELED'::core.download_status
      ELSE status
    END,
    finished_at = CASE
      WHEN status IN ('PENDING', 'PROCESSING', 'RETRYING') THEN now()
      ELSE finished_at
    END
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
RETURNING id, user_id, original_url, title, format, status, thumbnail_url, file_url, expires_at, duration_seconds, error_message, created_at, deleted_at, file_size_bytes, platform, provider, format_id, quality_label, progress_percent, downloaded_bytes, total_bytes, speed_bps, eta_seconds, started_at, finished_at, uploader, format_height
`

type CancelDownloadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Cancelar é idempotente: o filtro de status está no SET, não no WHERE. Com ele
// no WHERE, clicar em cancelar meio segundo depois de o download falhar sozinho
// não casava linha nenhuma e a tela cuspia "não pode mais ser cancelado" — um
// erro sobre uma corrida que o usuário não provocou nem pode evitar. Agora a
// linha sempre volta: quem já terminou apenas mantém o status que tinha, e a
// resposta diz qual é.
func (q *Queries) CancelDownload(ctx context.Context, arg CancelDownloadParams) (Download, error) {
	row := q.db.QueryRow(ctx, cancelDownload, arg.ID, arg.UserID)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OriginalUrl,
		&i.Title,
		&i.Format,
		&i.Status,
		&i.ThumbnailUrl,
		&i.FileUrl,
		&i.ExpiresAt,
		&i.DurationSeconds,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.FileSizeBytes,
		&i.Platform,
		&i.Provider,
		&i.FormatID,
		&i.QualityLabel,
		&i.ProgressPercent,
		&i.DownloadedBytes,
		&i.TotalBytes,
		&i.SpeedBps,
		&i.EtaSeconds,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Uploader,
		&i.FormatHeight,
	)
	return i, err
}

const countDownloadsByUser = `-- name: CountDownloadsByUser :one
SELECT COUNT(*) FROM downloads
WHERE user_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) CountDownloadsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDownloadsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDownload = `-- name: CreateDownload :one
INSERT INTO downloads (
  id, user_id, original_url, title, format, status, thumbnail_url, file_url, expires_at, duration_seconds, error_message
)
VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, user_id, original_url, title, format, status, thumbnail_url, file_url, expires_at, duration_seconds, error_message, created_at, deleted_at, file_size_bytes, platform, provider, format_id, quality_label, progress_percent, downloaded_bytes, total_bytes, speed_bps, eta_seconds, started_at, finished_at, uploader, format_height
`

type CreateDownloadParams struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	OriginalUrl     string             `json:"original_url"`
	Title           string             `json:"title"`
	Format          CoreFormatType     `json:"format"`
	Status          CoreDownloadStatus `json:"status"`
	ThumbnailUrl    pgtype.Text        `json:"thumbnail_url"`
	FileUrl         pgtype.Text        `json:"file_url"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	DurationSeconds pgtype.Int4        `json:"duration_seconds"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
}

func (q *Queries) CreateDownload(ctx context.Context, arg CreateDownloadParams) (Download, error) {
	row := q.db.QueryRow(ctx, createDownload,
		arg.ID,
		arg.UserID,
		arg.OriginalUrl,
		arg.Title,
		arg.Format,
		arg.Status,
		arg.ThumbnailUrl,
		arg.FileUrl,
		arg.ExpiresAt,
		arg.DurationSeconds,
		arg.ErrorMessage,
	)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OriginalUrl,
		&i.Title,
		&i.Format,
		&i.Status,
		&i.ThumbnailUrl,
		&i.FileUrl,
		&i.ExpiresAt,
		&i.DurationSeconds,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.FileSizeBytes,
		&i.Platform,
		&i.Provider,
		&i.FormatID,
		&i.QualityLabel,
		&i.ProgressPercent,
		&i.DownloadedBytes,
		&i.TotalBytes,
		&i.SpeedBps,
		&i.EtaSeconds,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Uploader,
		&i.FormatHeight,
	)
	return i, err
}

const createMediaDownload = `-- name: CreateMediaDownload :one
INSERT INTO downloads (
  id, user_id, original_url, title, format, status,
  thumbnail_url, duration_seconds, platform, provider,
  format_id, quality_label, uploader, total_bytes, format_height
)
VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, user_id, original_url, title, format, status, thumbnail_url, file_url, expires_at, duration_seconds, error_message, created_at, deleted_at, file_size_bytes, platform, provider, format_id, quality_label, progress_percent, downloaded_bytes, total_bytes, speed_bps, eta_seconds, started_at, finished_at, uploader, format_height
`

type CreateMediaDownloadParams struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	OriginalUrl     string             `json:"original_url"`
	Title           string             `json:"title"`
	Format          CoreFormatType     `json:"format"`
	Status          CoreDownloadStatus `json:"status"`
	ThumbnailUrl    pgtype.Text        `json:"thumbnail_url"`
	DurationSeconds pgtype.Int4        `json:"duration_seconds"`
	Platform        string             `json:"platform"`
	Provider        pgtype.Text        `json:"provider"`
	FormatID        pgtype.Text        `json:"format_id"`
	QualityLabel    pgtype.Text        `json:"quality_label"`
	Uploader        pgtype.Text        `json:"uploader"`
	TotalBytes      int64              `json:"total_bytes"`
	FormatHeight    int32              `json:"format_height"`
}

func (q *Queries) CreateMediaDownload(ctx context.Context, arg CreateMediaDownloadParams) (Download, error) {
	row := q.db.QueryRow(ctx, createMediaDownload,
		arg.ID,
		arg.UserID,
		arg.OriginalUrl,
		arg.Title,
		arg.Format,
		arg.Status,
		arg.ThumbnailUrl,
		arg.DurationSeconds,
		arg.Platform,
		arg.Provider,
		arg.FormatID,
		arg.QualityLabel,
		arg.Uploader,
		arg.TotalBytes,
		arg.FormatHeight,
	)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OriginalUrl,
		&i.Title,
		&i.Format,
		&i.Status,
		&i.ThumbnailUrl,
		&i.FileUrl,
		&i.ExpiresAt,
		&i.DurationSeconds,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.FileSizeBytes,
		&i.Platform,
		&i.Provider,
		&i.FormatID,
		&i.QualityLabel,
		&i.ProgressPercent,
		&i.DownloadedBytes,
		&i.TotalBytes,
		&i.SpeedBps,
		&i.EtaSeconds,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Uploader,
		&i.FormatHeight,
	)
	return i, err
}

const deleteDownload = `-- name: DeleteDownload :exec
UPDATE downloads
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteDownload(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDownload, id)
	return err
}

const getDownloadByID = `-- name: GetDownloadByID :one
SELECT id, user_id, original_url, title, format, status, thumbnail_url, file_url, expires_at, duration_seconds, error_message, created_at, deleted_at, file_size_bytes, platform, provider, format_id, quality_label, progress_percent, downloaded_bytes, total_bytes, speed_bps, eta_seconds, started_at, finished_at, uploader, format_height FROM downloads
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetDownloadByID(ctx context.Context, id uuid.UUID) (Download, error) {
	row := q.db.QueryRow(ctx, getDownloadByID, id)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OriginalUrl,
		&i.Title,
		&i.Format,
		&i.Status,
		&i.ThumbnailUrl,
		&i.FileUrl,
		&i.ExpiresAt,
		&i.DurationSeconds,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.FileSizeBytes,
		&i.Platform,
		&i.Provider,
		&i.FormatID,
		&i.QualityLabel,
		&i.ProgressPercent,
		&i.DownloadedBytes,
		&i.TotalBytes,
		&i.SpeedBps,
		&i.EtaSeconds,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Uploader,
		&i.FormatHeight,
	)
	return i, err
}

const getDownloadsByUser = `-- name: GetDownloadsByUser :many
SELECT id, user_id, original_url, title, format, status, thumbnail_url, file_url, expires_at, duration_seconds, error_message, created_at, deleted_at, file_size_bytes, platform, provider, format_id, quality_label, progress_percent, downloaded_bytes, total_bytes, speed_bps, eta_seconds, started_at, finished_at, uploader, format_height FROM downloads
WHERE user_id = $1 
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetDownloadsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetDownloadsByUser(ctx context.Context, arg GetDownloadsByUserParams) ([]Download, error) {
	rows, err := q.db.Query(ctx, getDownloadsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Download{}
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OriginalUrl,
			&i.Title,
			&i.Format,
			&i.Status,
			&i.ThumbnailUrl,
			&i.FileUrl,
			&i.ExpiresAt,
			&i.DurationSeconds,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.FileSizeBytes,
			&i.Platform,
			&i.Provider,
			&i.FormatID,
			&i.QualityLabel,
			&i.ProgressPercent,
			&i.DownloadedBytes,
			&i.TotalBytes,
			&i.SpeedBps,
			&i.EtaSeconds,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Uploader,
			&i.FormatHeight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDownloadsExpired = `-- name: GetDownloadsExpired :many
SELECT id, user_id, original_url, title, format, status, thumbnail_url, file_url, expires_at, duration_seconds, error_message, created_at, deleted_at, file_size_bytes, platform, provider, format_id, quality_label, progress_percent, downloaded_bytes, total_bytes, speed_bps, eta_seconds, started_at, finished_at, uploader, format_height
FROM downloads
WHERE status = 'COMPLETED'
  AND deleted_at IS NULL
  AND expires_at IS NOT NULL
  AND expires_at <= NOW()
`

func (q *Queries) GetDownloadsExpired(ctx context.Context) ([]Download, error) {
	rows, err := q.db.Query(ctx, getDownloadsExpired)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Download{}
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OriginalUrl,
			&i.Title,
			&i.Format,
			&i.Status,
			&i.ThumbnailUrl,
			&i.FileUrl,
			&i.ExpiresAt,
			&i.DurationSeconds,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.FileSizeBytes,
			&i.Platform,
			&i.Provider,
			&i.FormatID,
			&i.QualityLabel,
			&i.ProgressPercent,
			&i.DownloadedBytes,
			&i.TotalBytes,
			&i.SpeedBps,
			&i.EtaSeconds,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Uploader,
			&i.FormatHeight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDownloadFinished = `-- name: MarkDownloadFinished :exec
UPDATE downloads
SET status = $2, error_message = $3, finished_at = now()
WHERE id = $1
`

type MarkDownloadFinishedParams struct {
	ID           uuid.UUID          `json:"id"`
	Status       CoreDownloadStatus `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
}

func (q *Queries) MarkDownloadFinished(ctx context.Context, arg MarkDownloadFinishedParams) error {
	_, err := q.db.Exec(ctx, markDownloadFinished, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}

const markDownloadStarted = `-- name: MarkDownloadStarted :exec
UPDATE downloads
SET status = 'PROCESSING', started_at = now(), error_message = NULL
WHERE id = $1
`

func (q *Queries) MarkDownloadStarted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markDownloadStarted, id)
	return err
}

const setDownloadFileSize = `-- name: SetDownloadFileSize :exec
UPDATE downloads
SET file_size_bytes = $2
WHERE id = $1
`

type SetDownloadFileSizeParams struct {
	ID            uuid.UUID `json:"id"`
	FileSizeBytes int64     `json:"file_size_bytes"`
}

// Gravado pelo worker logo após o upload. É o que sustenta as métricas de
// armazenamento do painel: sem isto, o total do storage fica zerado para sempre.
func (q *Queries) SetDownloadFileSize(ctx context.Context, arg SetDownloadFileSizeParams) error {
	_, err := q.db.Exec(ctx, setDownloadFileSize, arg.ID, arg.FileSizeBytes)
	return err
}

const updateDownload = `-- name: UpdateDownload :exec
UPDATE downloads
SET
  status = $2,
  file_url = $3,
  thumbnail_url = $4,
  expires_at = $5,
  error_message = $6
WHERE id = $1
`

type UpdateDownloadParams struct {
	ID           uuid.UUID          `json:"id"`
	Status       CoreDownloadStatus `json:"status"`
	FileUrl      pgtype.Text        `json:"file_url"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	ErrorMessage pgtype.Text        `json:"error_message"`
}

func (q *Queries) UpdateDownload(ctx context.Context, arg UpdateDownloadParams) error {
	_, err := q.db.Exec(ctx, updateDownload,
		arg.ID,
		arg.Status,
		arg.FileUrl,
		arg.ThumbnailUrl,
		arg.ExpiresAt,
		arg.ErrorMessage,
	)
	return err
}

const updateDownloadProgress = `-- name: UpdateDownloadProgress :exec
UPDATE downloads
SET
  progress_percent = $2,
  downloaded_bytes = $3,
  total_bytes = GREATEST(total_bytes, $4),
  speed_bps = $5,
  eta_seconds = $6
WHERE id = $1
`

type UpdateDownloadProgressParams struct {
	ID              uuid.UUID      `json:"id"`
	ProgressPercent pgtype.Numeric `json:"progress_percent"`
	DownloadedBytes int64          `json:"downloaded_bytes"`
	TotalBytes      int64          `json:"total_bytes"`
	SpeedBps        int64          `json:"speed_bps"`
	EtaSeconds      int32          `json:"eta_seconds"`
}

// Gravado durante o download. Escreve pouco de propósito: o tempo real vai por
// SSE, e isto é só o último estado conhecido para a tela reabrir no meio.
func (q *Queries) UpdateDownloadProgress(ctx context.Context, arg UpdateDownloadProgressParams) error {
	_, err := q.db.Exec(ctx, updateDownloadProgress,
		arg.ID,
		arg.ProgressPercent,
		arg.DownloadedBytes,
		arg.TotalBytes,
		arg.SpeedBps,
		arg.EtaSeconds,
	)
	return err
}

const updateDownloadStatus = `-- name: UpdateDownloadStatus :exec
UPDATE downloads
SET status = $2, error_message = $3
WHERE id = $1
`

type UpdateDownloadStatusParams struct {
	ID           uuid.UUID          `json:"id"`
	Status       CoreDownloadStatus `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
}

func (q *Queries) UpdateDownloadStatus(ctx context.Context, arg UpdateDownloadStatusParams) error {
	_, err := q.db.Exec(ctx, updateDownloadStatus, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}
