// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: downloads.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDownloadsByUser = `-- name: CountDownloadsByUser :one
SELECT COUNT(*) FROM downloads
WHERE user_id = $1
`

func (q *Queries) CountDownloadsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDownloadsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDownload = `-- name: CreateDownload :one
INSERT INTO downloads (
  id, user_id, original_url, title, format, status, thumbnail_url, file_url, expires_at, duration_seconds, error_message
)
VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, user_id, original_url, title, format, status, thumbnail_url, file_url, expires_at, duration_seconds, error_message, created_at
`

type CreateDownloadParams struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	OriginalUrl     string             `json:"original_url"`
	Title           string             `json:"title"`
	Format          CoreFormatType     `json:"format"`
	Status          CoreDownloadStatus `json:"status"`
	ThumbnailUrl    pgtype.Text        `json:"thumbnail_url"`
	FileUrl         pgtype.Text        `json:"file_url"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	DurationSeconds pgtype.Int4        `json:"duration_seconds"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
}

func (q *Queries) CreateDownload(ctx context.Context, arg CreateDownloadParams) (Download, error) {
	row := q.db.QueryRow(ctx, createDownload,
		arg.ID,
		arg.UserID,
		arg.OriginalUrl,
		arg.Title,
		arg.Format,
		arg.Status,
		arg.ThumbnailUrl,
		arg.FileUrl,
		arg.ExpiresAt,
		arg.DurationSeconds,
		arg.ErrorMessage,
	)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OriginalUrl,
		&i.Title,
		&i.Format,
		&i.Status,
		&i.ThumbnailUrl,
		&i.FileUrl,
		&i.ExpiresAt,
		&i.DurationSeconds,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDownload = `-- name: DeleteDownload :exec
DELETE FROM downloads
WHERE id = $1
`

func (q *Queries) DeleteDownload(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDownload, id)
	return err
}

const getDownloadByID = `-- name: GetDownloadByID :one
SELECT id, user_id, original_url, title, format, status, thumbnail_url, file_url, expires_at, duration_seconds, error_message, created_at FROM downloads
WHERE id = $1
`

func (q *Queries) GetDownloadByID(ctx context.Context, id uuid.UUID) (Download, error) {
	row := q.db.QueryRow(ctx, getDownloadByID, id)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OriginalUrl,
		&i.Title,
		&i.Format,
		&i.Status,
		&i.ThumbnailUrl,
		&i.FileUrl,
		&i.ExpiresAt,
		&i.DurationSeconds,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getDownloadsByUser = `-- name: GetDownloadsByUser :many
SELECT id, user_id, original_url, title, format, status, thumbnail_url, file_url, expires_at, duration_seconds, error_message, created_at FROM downloads
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetDownloadsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetDownloadsByUser(ctx context.Context, arg GetDownloadsByUserParams) ([]Download, error) {
	rows, err := q.db.Query(ctx, getDownloadsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Download{}
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OriginalUrl,
			&i.Title,
			&i.Format,
			&i.Status,
			&i.ThumbnailUrl,
			&i.FileUrl,
			&i.ExpiresAt,
			&i.DurationSeconds,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDownloadsExpired = `-- name: GetDownloadsExpired :many
SELECT id, user_id, original_url, title, format, status, thumbnail_url, file_url, expires_at, duration_seconds, error_message, created_at
FROM downloads
WHERE status = 'COMPLETED'
  AND expires_at IS NOT NULL
  AND expires_at <= NOW()
`

func (q *Queries) GetDownloadsExpired(ctx context.Context) ([]Download, error) {
	rows, err := q.db.Query(ctx, getDownloadsExpired)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Download{}
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OriginalUrl,
			&i.Title,
			&i.Format,
			&i.Status,
			&i.ThumbnailUrl,
			&i.FileUrl,
			&i.ExpiresAt,
			&i.DurationSeconds,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDownload = `-- name: UpdateDownload :exec
UPDATE downloads
SET
  status = $2,
  file_url = $3,
  thumbnail_url = $4,
  expires_at = $5,
  error_message = $6
WHERE id = $1
`

type UpdateDownloadParams struct {
	ID           uuid.UUID          `json:"id"`
	Status       CoreDownloadStatus `json:"status"`
	FileUrl      pgtype.Text        `json:"file_url"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	ErrorMessage pgtype.Text        `json:"error_message"`
}

func (q *Queries) UpdateDownload(ctx context.Context, arg UpdateDownloadParams) error {
	_, err := q.db.Exec(ctx, updateDownload,
		arg.ID,
		arg.Status,
		arg.FileUrl,
		arg.ThumbnailUrl,
		arg.ExpiresAt,
		arg.ErrorMessage,
	)
	return err
}

const updateDownloadStatus = `-- name: UpdateDownloadStatus :exec
UPDATE downloads
SET status = $2, error_message = $3
WHERE id = $1
`

type UpdateDownloadStatusParams struct {
	ID           uuid.UUID          `json:"id"`
	Status       CoreDownloadStatus `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
}

func (q *Queries) UpdateDownloadStatus(ctx context.Context, arg UpdateDownloadStatusParams) error {
	_, err := q.db.Exec(ctx, updateDownloadStatus, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}
