// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: integrations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countIntegrationActiveDownloads = `-- name: CountIntegrationActiveDownloads :one
SELECT COUNT(*) FROM downloads
WHERE user_id = $1
  AND deleted_at IS NULL
  AND status IN ('PENDING', 'PROCESSING', 'RETRYING')
`

// Trabalho em voo. A cota diária sozinha permitiria disparar tudo de uma vez e
// ocupar o worker inteiro; este número é o que sustenta o limite de simultâneos.
func (q *Queries) CountIntegrationActiveDownloads(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countIntegrationActiveDownloads, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIntegrationDownloads = `-- name: CountIntegrationDownloads :one
SELECT COUNT(*) FROM downloads
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ($2::core.download_status IS NULL
       OR status = $2::core.download_status)
  AND ($3::text IS NULL OR platform = $3::text)
  AND (
    $4::text IS NULL
    OR lower(title) LIKE '%' || lower($4::text) || '%'
    OR lower(original_url) LIKE '%' || lower($4::text) || '%'
  )
`

type CountIntegrationDownloadsParams struct {
	UserID   uuid.UUID              `json:"user_id"`
	Status   NullCoreDownloadStatus `json:"status"`
	Platform pgtype.Text            `json:"platform"`
	Search   pgtype.Text            `json:"search"`
}

func (q *Queries) CountIntegrationDownloads(ctx context.Context, arg CountIntegrationDownloadsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIntegrationDownloads,
		arg.UserID,
		arg.Status,
		arg.Platform,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIntegrationDownloadsToday = `-- name: CountIntegrationDownloadsToday :one
SELECT COUNT(*) FROM downloads
WHERE user_id = $1
  AND deleted_at IS NULL
  AND created_at >= TIMEZONE('UTC', TIMEZONE('America/Sao_Paulo', CURRENT_DATE))
  AND created_at <  TIMEZONE('UTC', TIMEZONE('America/Sao_Paulo', CURRENT_DATE + INTERVAL '1 day'))
`

// Cota do dia. Mesmo corte de fuso do contador do usuário comum.
func (q *Queries) CountIntegrationDownloadsToday(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countIntegrationDownloadsToday, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIntegrationRequests = `-- name: CountIntegrationRequests :one
SELECT COUNT(*) FROM integration_requests
WHERE integration_id = $1
  AND ($2::text IS NULL OR ip = $2::text)
  AND ($3::int IS NULL
       OR status_code / 100 = $3::int)
  AND ($4::text IS NULL OR path LIKE '%' || $4::text || '%')
  AND ($5::text IS NULL OR error_code = $5::text)
`

type CountIntegrationRequestsParams struct {
	IntegrationID uuid.UUID   `json:"integration_id"`
	Ip            pgtype.Text `json:"ip"`
	StatusClass   pgtype.Int4 `json:"status_class"`
	Path          pgtype.Text `json:"path"`
	ErrorCode     pgtype.Text `json:"error_code"`
}

func (q *Queries) CountIntegrationRequests(ctx context.Context, arg CountIntegrationRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIntegrationRequests,
		arg.IntegrationID,
		arg.Ip,
		arg.StatusClass,
		arg.Path,
		arg.ErrorCode,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIntegrations = `-- name: CountIntegrations :one
SELECT COUNT(*) FROM integrations i
WHERE i.deleted_at IS NULL
  AND (
    $1::text IS NULL
    OR lower(i.name) LIKE '%' || lower($1::text) || '%'
    OR lower(COALESCE(i.description, '')) LIKE '%' || lower($1::text) || '%'
  )
  AND ($2::boolean IS NULL OR i.active = $2::boolean)
`

type CountIntegrationsParams struct {
	Search pgtype.Text `json:"search"`
	Active pgtype.Bool `json:"active"`
}

func (q *Queries) CountIntegrations(ctx context.Context, arg CountIntegrationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIntegrations, arg.Search, arg.Active)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWebhookDeliveries = `-- name: CountWebhookDeliveries :one
SELECT COUNT(*) FROM integration_webhook_deliveries d
WHERE d.integration_id = $1
  AND ($2::core.webhook_delivery_status IS NULL
       OR d.status = $2::core.webhook_delivery_status)
  AND ($3::text IS NULL OR d.event_type = $3::text)
  AND ($4::uuid IS NULL OR d.download_id = $4::uuid)
`

type CountWebhookDeliveriesParams struct {
	IntegrationID uuid.UUID                     `json:"integration_id"`
	Status        NullCoreWebhookDeliveryStatus `json:"status"`
	EventType     pgtype.Text                   `json:"event_type"`
	DownloadID    pgtype.UUID                   `json:"download_id"`
}

func (q *Queries) CountWebhookDeliveries(ctx context.Context, arg CountWebhookDeliveriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhookDeliveries,
		arg.IntegrationID,
		arg.Status,
		arg.EventType,
		arg.DownloadID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIntegration = `-- name: CreateIntegration :one

INSERT INTO integrations (
  id, user_id, name, description, callback_base_url, daily_limit,
  max_file_size_bytes, rate_limit_per_minute, max_concurrent_downloads,
  allowed_ips, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, name, description, callback_base_url, daily_limit, max_file_size_bytes, rate_limit_per_minute, max_concurrent_downloads, allowed_ips, active, created_by, created_at, updated_at, deleted_at
`

type CreateIntegrationParams struct {
	ID                     uuid.UUID   `json:"id"`
	UserID                 uuid.UUID   `json:"user_id"`
	Name                   string      `json:"name"`
	Description            pgtype.Text `json:"description"`
	CallbackBaseUrl        pgtype.Text `json:"callback_base_url"`
	DailyLimit             int32       `json:"daily_limit"`
	MaxFileSizeBytes       int64       `json:"max_file_size_bytes"`
	RateLimitPerMinute     int32       `json:"rate_limit_per_minute"`
	MaxConcurrentDownloads int32       `json:"max_concurrent_downloads"`
	AllowedIps             []string    `json:"allowed_ips"`
	CreatedBy              pgtype.UUID `json:"created_by"`
}

// ---------------------------------------------------------------------------
// Integrações
// ---------------------------------------------------------------------------
func (q *Queries) CreateIntegration(ctx context.Context, arg CreateIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, createIntegration,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.CallbackBaseUrl,
		arg.DailyLimit,
		arg.MaxFileSizeBytes,
		arg.RateLimitPerMinute,
		arg.MaxConcurrentDownloads,
		arg.AllowedIps,
		arg.CreatedBy,
	)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CallbackBaseUrl,
		&i.DailyLimit,
		&i.MaxFileSizeBytes,
		&i.RateLimitPerMinute,
		&i.MaxConcurrentDownloads,
		&i.AllowedIps,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createIntegrationAPIKey = `-- name: CreateIntegrationAPIKey :one

INSERT INTO integration_api_keys (
  id, integration_id, label, key_prefix, key_hash, last_four, expires_at, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, integration_id, label, key_prefix, key_hash, last_four, revoked_at, revoked_reason, expires_at, last_used_at, last_used_ip, created_by, created_at
`

type CreateIntegrationAPIKeyParams struct {
	ID            uuid.UUID          `json:"id"`
	IntegrationID uuid.UUID          `json:"integration_id"`
	Label         string             `json:"label"`
	KeyPrefix     string             `json:"key_prefix"`
	KeyHash       string             `json:"key_hash"`
	LastFour      string             `json:"last_four"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
}

// ---------------------------------------------------------------------------
// Chaves de API
// ---------------------------------------------------------------------------
func (q *Queries) CreateIntegrationAPIKey(ctx context.Context, arg CreateIntegrationAPIKeyParams) (IntegrationApiKey, error) {
	row := q.db.QueryRow(ctx, createIntegrationAPIKey,
		arg.ID,
		arg.IntegrationID,
		arg.Label,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.LastFour,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i IntegrationApiKey
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Label,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.LastFour,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createIntegrationRequest = `-- name: CreateIntegrationRequest :exec

INSERT INTO integration_requests (
  integration_id, api_key_id, method, path, status_code,
  ip, user_agent, duration_ms, error_code, download_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateIntegrationRequestParams struct {
	IntegrationID uuid.UUID   `json:"integration_id"`
	ApiKeyID      pgtype.UUID `json:"api_key_id"`
	Method        string      `json:"method"`
	Path          string      `json:"path"`
	StatusCode    int32       `json:"status_code"`
	Ip            string      `json:"ip"`
	UserAgent     string      `json:"user_agent"`
	DurationMs    int32       `json:"duration_ms"`
	ErrorCode     pgtype.Text `json:"error_code"`
	DownloadID    pgtype.UUID `json:"download_id"`
}

// ---------------------------------------------------------------------------
// Auditoria de requisições
// ---------------------------------------------------------------------------
func (q *Queries) CreateIntegrationRequest(ctx context.Context, arg CreateIntegrationRequestParams) error {
	_, err := q.db.Exec(ctx, createIntegrationRequest,
		arg.IntegrationID,
		arg.ApiKeyID,
		arg.Method,
		arg.Path,
		arg.StatusCode,
		arg.Ip,
		arg.UserAgent,
		arg.DurationMs,
		arg.ErrorCode,
		arg.DownloadID,
	)
	return err
}

const createIntegrationWebhook = `-- name: CreateIntegrationWebhook :one

INSERT INTO integration_webhooks (
  id, integration_id, url, secret, events, include_progress
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, integration_id, url, secret, events, include_progress, active, last_delivery_at, last_status_code, last_error, consecutive_failures, disabled_reason, created_at, updated_at, deleted_at
`

type CreateIntegrationWebhookParams struct {
	ID              uuid.UUID `json:"id"`
	IntegrationID   uuid.UUID `json:"integration_id"`
	Url             string    `json:"url"`
	Secret          string    `json:"secret"`
	Events          []string  `json:"events"`
	IncludeProgress bool      `json:"include_progress"`
}

// ---------------------------------------------------------------------------
// Webhooks
// ---------------------------------------------------------------------------
func (q *Queries) CreateIntegrationWebhook(ctx context.Context, arg CreateIntegrationWebhookParams) (IntegrationWebhook, error) {
	row := q.db.QueryRow(ctx, createIntegrationWebhook,
		arg.ID,
		arg.IntegrationID,
		arg.Url,
		arg.Secret,
		arg.Events,
		arg.IncludeProgress,
	)
	var i IntegrationWebhook
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.IncludeProgress,
		&i.Active,
		&i.LastDeliveryAt,
		&i.LastStatusCode,
		&i.LastError,
		&i.ConsecutiveFailures,
		&i.DisabledReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createServiceUser = `-- name: CreateServiceUser :one


INSERT INTO users (
  id, full_name, email, hashed_password, plan, daily_limit,
  active, is_verified, kind, password_changed_at
)
VALUES ($1, $2, $3, $4, 'enterprise', 0, true, true, 'service', now())
RETURNING id, full_name, photo_url, email, hashed_password, password_changed_at, active, plan, daily_limit, last_login, is_verified, created_at, updated_at, role, deleted_at, kind
`

type CreateServiceUserParams struct {
	ID             uuid.UUID `json:"id"`
	FullName       string    `json:"full_name"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
}

// Consultas da seção de integrações: as contas de SISTEMA que consomem a
// plataforma por API, as chaves que as autenticam, os webhooks que avisam o
// sistema integrado e a auditoria de tudo que chegou por essa porta.
// ---------------------------------------------------------------------------
// Conta de serviço
// ---------------------------------------------------------------------------
// A conta de serviço nasce sem senha utilizável: `hashed_password` recebe um
// valor que nenhum bcrypt aceita como válido, então nem uma senha em branco
// autentica. Quem prova identidade aqui é a chave de API.
//
// `daily_limit` fica em zero porque a cota da integração vive na linha de
// `integrations`; deixar um número aqui criaria dois limites com o mesmo nome.
func (q *Queries) CreateServiceUser(ctx context.Context, arg CreateServiceUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createServiceUser,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.HashedPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.PhotoUrl,
		&i.Email,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.Active,
		&i.Plan,
		&i.DailyLimit,
		&i.LastLogin,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.DeletedAt,
		&i.Kind,
	)
	return i, err
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one

INSERT INTO integration_webhook_deliveries (
  id, webhook_id, integration_id, event_type, download_id, payload
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, webhook_id, integration_id, event_type, download_id, payload, status, attempts, last_status_code, last_error, duration_ms, delivered_at, created_at
`

type CreateWebhookDeliveryParams struct {
	ID            uuid.UUID   `json:"id"`
	WebhookID     uuid.UUID   `json:"webhook_id"`
	IntegrationID uuid.UUID   `json:"integration_id"`
	EventType     string      `json:"event_type"`
	DownloadID    pgtype.UUID `json:"download_id"`
	Payload       []byte      `json:"payload"`
}

// ---------------------------------------------------------------------------
// Entregas
// ---------------------------------------------------------------------------
func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (IntegrationWebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery,
		arg.ID,
		arg.WebhookID,
		arg.IntegrationID,
		arg.EventType,
		arg.DownloadID,
		arg.Payload,
	)
	var i IntegrationWebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.IntegrationID,
		&i.EventType,
		&i.DownloadID,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastStatusCode,
		&i.LastError,
		&i.DurationMs,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const disableIntegrationWebhook = `-- name: DisableIntegrationWebhook :exec
UPDATE integration_webhooks
SET active = false, disabled_reason = $2, updated_at = now()
WHERE id = $1
`

type DisableIntegrationWebhookParams struct {
	ID             uuid.UUID   `json:"id"`
	DisabledReason pgtype.Text `json:"disabled_reason"`
}

func (q *Queries) DisableIntegrationWebhook(ctx context.Context, arg DisableIntegrationWebhookParams) error {
	_, err := q.db.Exec(ctx, disableIntegrationWebhook, arg.ID, arg.DisabledReason)
	return err
}

const getIntegrationAPIKey = `-- name: GetIntegrationAPIKey :one
SELECT id, integration_id, label, key_prefix, key_hash, last_four, revoked_at, revoked_reason, expires_at, last_used_at, last_used_ip, created_by, created_at FROM integration_api_keys
WHERE id = $1
`

func (q *Queries) GetIntegrationAPIKey(ctx context.Context, id uuid.UUID) (IntegrationApiKey, error) {
	row := q.db.QueryRow(ctx, getIntegrationAPIKey, id)
	var i IntegrationApiKey
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Label,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.LastFour,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getIntegrationByID = `-- name: GetIntegrationByID :one
SELECT id, user_id, name, description, callback_base_url, daily_limit, max_file_size_bytes, rate_limit_per_minute, max_concurrent_downloads, allowed_ips, active, created_by, created_at, updated_at, deleted_at FROM integrations
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetIntegrationByID(ctx context.Context, id uuid.UUID) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegrationByID, id)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CallbackBaseUrl,
		&i.DailyLimit,
		&i.MaxFileSizeBytes,
		&i.RateLimitPerMinute,
		&i.MaxConcurrentDownloads,
		&i.AllowedIps,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getIntegrationByUserID = `-- name: GetIntegrationByUserID :one
SELECT id, user_id, name, description, callback_base_url, daily_limit, max_file_size_bytes, rate_limit_per_minute, max_concurrent_downloads, allowed_ips, active, created_by, created_at, updated_at, deleted_at FROM integrations
WHERE user_id = $1
  AND deleted_at IS NULL
`

// Usada pelo despachante de webhooks: o evento de download carrega o
// `user_id`, e é por ele que se descobre se aquele download pertence a uma
// integração.
func (q *Queries) GetIntegrationByUserID(ctx context.Context, userID uuid.UUID) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegrationByUserID, userID)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CallbackBaseUrl,
		&i.DailyLimit,
		&i.MaxFileSizeBytes,
		&i.RateLimitPerMinute,
		&i.MaxConcurrentDownloads,
		&i.AllowedIps,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getIntegrationKeyByHash = `-- name: GetIntegrationKeyByHash :one
SELECT
  k.id                AS key_id,
  k.label             AS key_label,
  k.key_prefix        AS key_prefix,
  k.revoked_at        AS key_revoked_at,
  k.expires_at        AS key_expires_at,
  i.id, i.user_id, i.name, i.description, i.callback_base_url, i.daily_limit, i.max_file_size_bytes, i.rate_limit_per_minute, i.max_concurrent_downloads, i.allowed_ips, i.active, i.created_by, i.created_at, i.updated_at, i.deleted_at,
  u.id, u.full_name, u.photo_url, u.email, u.hashed_password, u.password_changed_at, u.active, u.plan, u.daily_limit, u.last_login, u.is_verified, u.created_at, u.updated_at, u.role, u.deleted_at, u.kind
FROM integration_api_keys k
JOIN integrations i ON i.id = k.integration_id
JOIN users u ON u.id = i.user_id
WHERE k.key_hash = $1
LIMIT 1
`

type GetIntegrationKeyByHashRow struct {
	KeyID        uuid.UUID          `json:"key_id"`
	KeyLabel     string             `json:"key_label"`
	KeyPrefix    string             `json:"key_prefix"`
	KeyRevokedAt pgtype.Timestamptz `json:"key_revoked_at"`
	KeyExpiresAt pgtype.Timestamptz `json:"key_expires_at"`
	Integration  Integration        `json:"integration"`
	User         User               `json:"user"`
}

// O caminho de autenticação, e é por isso que traz tudo de uma vez: a chave, a
// integração e a conta de serviço. Três consultas aqui seriam três idas ao
// banco em CADA requisição da API de integrações.
//
// A busca é pelo hash, que tem índice único. A chave em claro nunca é
// comparada contra nada no banco.
func (q *Queries) GetIntegrationKeyByHash(ctx context.Context, keyHash string) (GetIntegrationKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getIntegrationKeyByHash, keyHash)
	var i GetIntegrationKeyByHashRow
	err := row.Scan(
		&i.KeyID,
		&i.KeyLabel,
		&i.KeyPrefix,
		&i.KeyRevokedAt,
		&i.KeyExpiresAt,
		&i.Integration.ID,
		&i.Integration.UserID,
		&i.Integration.Name,
		&i.Integration.Description,
		&i.Integration.CallbackBaseUrl,
		&i.Integration.DailyLimit,
		&i.Integration.MaxFileSizeBytes,
		&i.Integration.RateLimitPerMinute,
		&i.Integration.MaxConcurrentDownloads,
		&i.Integration.AllowedIps,
		&i.Integration.Active,
		&i.Integration.CreatedBy,
		&i.Integration.CreatedAt,
		&i.Integration.UpdatedAt,
		&i.Integration.DeletedAt,
		&i.User.ID,
		&i.User.FullName,
		&i.User.PhotoUrl,
		&i.User.Email,
		&i.User.HashedPassword,
		&i.User.PasswordChangedAt,
		&i.User.Active,
		&i.User.Plan,
		&i.User.DailyLimit,
		&i.User.LastLogin,
		&i.User.IsVerified,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.Role,
		&i.User.DeletedAt,
		&i.User.Kind,
	)
	return i, err
}

const getIntegrationWebhook = `-- name: GetIntegrationWebhook :one
SELECT id, integration_id, url, secret, events, include_progress, active, last_delivery_at, last_status_code, last_error, consecutive_failures, disabled_reason, created_at, updated_at, deleted_at FROM integration_webhooks
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetIntegrationWebhook(ctx context.Context, id uuid.UUID) (IntegrationWebhook, error) {
	row := q.db.QueryRow(ctx, getIntegrationWebhook, id)
	var i IntegrationWebhook
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.IncludeProgress,
		&i.Active,
		&i.LastDeliveryAt,
		&i.LastStatusCode,
		&i.LastError,
		&i.ConsecutiveFailures,
		&i.DisabledReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWebhookDelivery = `-- name: GetWebhookDelivery :one
SELECT id, webhook_id, integration_id, event_type, download_id, payload, status, attempts, last_status_code, last_error, duration_ms, delivered_at, created_at FROM integration_webhook_deliveries
WHERE id = $1
`

func (q *Queries) GetWebhookDelivery(ctx context.Context, id uuid.UUID) (IntegrationWebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDelivery, id)
	var i IntegrationWebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.IntegrationID,
		&i.EventType,
		&i.DownloadID,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastStatusCode,
		&i.LastError,
		&i.DurationMs,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const integrationDownloadSummary = `-- name: IntegrationDownloadSummary :one
SELECT
  COUNT(*) FILTER (WHERE deleted_at IS NULL)::bigint AS total,
  COUNT(*) FILTER (
    WHERE deleted_at IS NULL
      AND created_at >= TIMEZONE('UTC', TIMEZONE('America/Sao_Paulo', CURRENT_DATE))
      AND created_at <  TIMEZONE('UTC', TIMEZONE('America/Sao_Paulo', CURRENT_DATE + INTERVAL '1 day'))
  )::bigint AS today,
  COUNT(*) FILTER (
    WHERE deleted_at IS NULL AND status IN ('PENDING', 'PROCESSING', 'RETRYING')
  )::bigint AS active,
  COUNT(*) FILTER (WHERE deleted_at IS NULL AND status = 'COMPLETED')::bigint AS completed,
  COUNT(*) FILTER (WHERE deleted_at IS NULL AND status = 'FAILED')::bigint AS failed,
  COUNT(*) FILTER (WHERE deleted_at IS NULL AND status = 'CANCELED')::bigint AS canceled,
  COALESCE(SUM(file_size_bytes) FILTER (
    WHERE deleted_at IS NULL AND status = 'COMPLETED'
  ), 0)::bigint AS storage_bytes,
  COALESCE(SUM(file_size_bytes) FILTER (WHERE deleted_at IS NULL), 0)::bigint AS transferred_bytes
FROM downloads
WHERE user_id = $1
`

type IntegrationDownloadSummaryRow struct {
	Total            int64 `json:"total"`
	Today            int64 `json:"today"`
	Active           int64 `json:"active"`
	Completed        int64 `json:"completed"`
	Failed           int64 `json:"failed"`
	Canceled         int64 `json:"canceled"`
	StorageBytes     int64 `json:"storage_bytes"`
	TransferredBytes int64 `json:"transferred_bytes"`
}

// Resumo da integração para a aba de visão geral.
func (q *Queries) IntegrationDownloadSummary(ctx context.Context, userID uuid.UUID) (IntegrationDownloadSummaryRow, error) {
	row := q.db.QueryRow(ctx, integrationDownloadSummary, userID)
	var i IntegrationDownloadSummaryRow
	err := row.Scan(
		&i.Total,
		&i.Today,
		&i.Active,
		&i.Completed,
		&i.Failed,
		&i.Canceled,
		&i.StorageBytes,
		&i.TransferredBytes,
	)
	return i, err
}

const integrationRequestStats = `-- name: IntegrationRequestStats :one
SELECT
  COUNT(*)::bigint AS total,
  COUNT(*) FILTER (WHERE status_code < 400)::bigint AS ok,
  COUNT(*) FILTER (WHERE status_code BETWEEN 400 AND 499)::bigint AS client_errors,
  COUNT(*) FILTER (WHERE status_code >= 500)::bigint AS server_errors,
  COUNT(*) FILTER (WHERE status_code = 429)::bigint AS throttled,
  COUNT(DISTINCT ip)::bigint AS unique_ips,
  COALESCE(AVG(duration_ms), 0)::int AS avg_duration_ms,
  COALESCE(MAX(duration_ms), 0)::int AS max_duration_ms
FROM integration_requests
WHERE integration_id = $1
  AND created_at >= now() - ($2::int * INTERVAL '1 hour')
`

type IntegrationRequestStatsParams struct {
	IntegrationID uuid.UUID `json:"integration_id"`
	WindowHours   int32     `json:"window_hours"`
}

type IntegrationRequestStatsRow struct {
	Total         int64 `json:"total"`
	Ok            int64 `json:"ok"`
	ClientErrors  int64 `json:"client_errors"`
	ServerErrors  int64 `json:"server_errors"`
	Throttled     int64 `json:"throttled"`
	UniqueIps     int64 `json:"unique_ips"`
	AvgDurationMs int32 `json:"avg_duration_ms"`
	MaxDurationMs int32 `json:"max_duration_ms"`
}

func (q *Queries) IntegrationRequestStats(ctx context.Context, arg IntegrationRequestStatsParams) (IntegrationRequestStatsRow, error) {
	row := q.db.QueryRow(ctx, integrationRequestStats, arg.IntegrationID, arg.WindowHours)
	var i IntegrationRequestStatsRow
	err := row.Scan(
		&i.Total,
		&i.Ok,
		&i.ClientErrors,
		&i.ServerErrors,
		&i.Throttled,
		&i.UniqueIps,
		&i.AvgDurationMs,
		&i.MaxDurationMs,
	)
	return i, err
}

const integrationTopErrors = `-- name: IntegrationTopErrors :many
SELECT
  COALESCE(error_code, 'sem_codigo') AS error_code,
  status_code,
  COUNT(*)::bigint AS occurrences,
  MAX(created_at) AS last_seen
FROM integration_requests
WHERE integration_id = $1
  AND status_code >= 400
  AND created_at >= now() - ($3::int * INTERVAL '1 hour')
GROUP BY error_code, status_code
ORDER BY occurrences DESC
LIMIT $2
`

type IntegrationTopErrorsParams struct {
	IntegrationID uuid.UUID `json:"integration_id"`
	Limit         int32     `json:"limit"`
	WindowHours   int32     `json:"window_hours"`
}

type IntegrationTopErrorsRow struct {
	ErrorCode   string      `json:"error_code"`
	StatusCode  int32       `json:"status_code"`
	Occurrences int64       `json:"occurrences"`
	LastSeen    interface{} `json:"last_seen"`
}

// Falhas agrupadas por CAUSA, não por texto. É por isso que `error_code` é
// gravado junto da resposta: o painel mostra "quota_exceeded: 42" em vez de
// quarenta e duas linhas iguais.
func (q *Queries) IntegrationTopErrors(ctx context.Context, arg IntegrationTopErrorsParams) ([]IntegrationTopErrorsRow, error) {
	rows, err := q.db.Query(ctx, integrationTopErrors, arg.IntegrationID, arg.Limit, arg.WindowHours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntegrationTopErrorsRow{}
	for rows.Next() {
		var i IntegrationTopErrorsRow
		if err := rows.Scan(
			&i.ErrorCode,
			&i.StatusCode,
			&i.Occurrences,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const integrationTopIPs = `-- name: IntegrationTopIPs :many
SELECT
  ip,
  COUNT(*)::bigint AS requests,
  COUNT(*) FILTER (WHERE status_code >= 400)::bigint AS errors,
  MAX(created_at) AS last_seen
FROM integration_requests
WHERE integration_id = $1
  AND created_at >= now() - ($3::int * INTERVAL '1 hour')
  AND ip <> ''
GROUP BY ip
ORDER BY requests DESC
LIMIT $2
`

type IntegrationTopIPsParams struct {
	IntegrationID uuid.UUID `json:"integration_id"`
	Limit         int32     `json:"limit"`
	WindowHours   int32     `json:"window_hours"`
}

type IntegrationTopIPsRow struct {
	Ip       string      `json:"ip"`
	Requests int64       `json:"requests"`
	Errors   int64       `json:"errors"`
	LastSeen interface{} `json:"last_seen"`
}

// De onde as chamadas vêm. É a resposta para "quem está batendo na minha API",
// que é exatamente o que se quer saber quando o volume sobe sem explicação.
func (q *Queries) IntegrationTopIPs(ctx context.Context, arg IntegrationTopIPsParams) ([]IntegrationTopIPsRow, error) {
	rows, err := q.db.Query(ctx, integrationTopIPs, arg.IntegrationID, arg.Limit, arg.WindowHours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntegrationTopIPsRow{}
	for rows.Next() {
		var i IntegrationTopIPsRow
		if err := rows.Scan(
			&i.Ip,
			&i.Requests,
			&i.Errors,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveIntegrationWebhooks = `-- name: ListActiveIntegrationWebhooks :many
SELECT id, integration_id, url, secret, events, include_progress, active, last_delivery_at, last_status_code, last_error, consecutive_failures, disabled_reason, created_at, updated_at, deleted_at FROM integration_webhooks
WHERE integration_id = $1
  AND deleted_at IS NULL
  AND active = true
ORDER BY created_at
`

// Consultada pelo despachante a cada evento de ciclo de vida. Só os ativos: um
// webhook desligado não deve nem gerar linha de entrega.
func (q *Queries) ListActiveIntegrationWebhooks(ctx context.Context, integrationID uuid.UUID) ([]IntegrationWebhook, error) {
	rows, err := q.db.Query(ctx, listActiveIntegrationWebhooks, integrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntegrationWebhook{}
	for rows.Next() {
		var i IntegrationWebhook
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.IncludeProgress,
			&i.Active,
			&i.LastDeliveryAt,
			&i.LastStatusCode,
			&i.LastError,
			&i.ConsecutiveFailures,
			&i.DisabledReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationAPIKeys = `-- name: ListIntegrationAPIKeys :many
SELECT id, integration_id, label, key_prefix, key_hash, last_four, revoked_at, revoked_reason, expires_at, last_used_at, last_used_ip, created_by, created_at FROM integration_api_keys
WHERE integration_id = $1
ORDER BY revoked_at IS NOT NULL, created_at DESC
`

func (q *Queries) ListIntegrationAPIKeys(ctx context.Context, integrationID uuid.UUID) ([]IntegrationApiKey, error) {
	rows, err := q.db.Query(ctx, listIntegrationAPIKeys, integrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntegrationApiKey{}
	for rows.Next() {
		var i IntegrationApiKey
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.Label,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.LastFour,
			&i.RevokedAt,
			&i.RevokedReason,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.LastUsedIp,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationDownloads = `-- name: ListIntegrationDownloads :many

SELECT id, user_id, original_url, title, format, status, thumbnail_url, file_url, expires_at, duration_seconds, error_message, created_at, deleted_at, file_size_bytes, platform, provider, format_id, quality_label, progress_percent, downloaded_bytes, total_bytes, speed_bps, eta_seconds, started_at, finished_at, uploader, format_height, error_detail FROM downloads
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ($4::core.download_status IS NULL
       OR status = $4::core.download_status)
  AND ($5::text IS NULL OR platform = $5::text)
  AND (
    $6::text IS NULL
    OR lower(title) LIKE '%' || lower($6::text) || '%'
    OR lower(original_url) LIKE '%' || lower($6::text) || '%'
  )
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListIntegrationDownloadsParams struct {
	UserID   uuid.UUID              `json:"user_id"`
	Limit    int32                  `json:"limit"`
	Offset   int32                  `json:"offset"`
	Status   NullCoreDownloadStatus `json:"status"`
	Platform pgtype.Text            `json:"platform"`
	Search   pgtype.Text            `json:"search"`
}

// ---------------------------------------------------------------------------
// Downloads da integração
// ---------------------------------------------------------------------------
// A listagem que a API de integrações e a aba de downloads do painel usam.
//
// Existe separada de GetDownloadsByUser porque um sistema integrado precisa
// filtrar: o caso normal dele é "me devolva o que ainda está em andamento" ou
// "o que falhou hoje", e sem filtro no servidor ele teria de paginar o
// histórico inteiro para descobrir isso.
func (q *Queries) ListIntegrationDownloads(ctx context.Context, arg ListIntegrationDownloadsParams) ([]Download, error) {
	rows, err := q.db.Query(ctx, listIntegrationDownloads,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Platform,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Download{}
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OriginalUrl,
			&i.Title,
			&i.Format,
			&i.Status,
			&i.ThumbnailUrl,
			&i.FileUrl,
			&i.ExpiresAt,
			&i.DurationSeconds,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.FileSizeBytes,
			&i.Platform,
			&i.Provider,
			&i.FormatID,
			&i.QualityLabel,
			&i.ProgressPercent,
			&i.DownloadedBytes,
			&i.TotalBytes,
			&i.SpeedBps,
			&i.EtaSeconds,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Uploader,
			&i.FormatHeight,
			&i.ErrorDetail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationRequests = `-- name: ListIntegrationRequests :many
SELECT id, integration_id, api_key_id, method, path, status_code, ip, user_agent, duration_ms, error_code, download_id, created_at FROM integration_requests
WHERE integration_id = $1
  AND ($4::text IS NULL OR ip = $4::text)
  AND ($5::int IS NULL
       OR status_code / 100 = $5::int)
  AND ($6::text IS NULL OR path LIKE '%' || $6::text || '%')
  AND ($7::text IS NULL OR error_code = $7::text)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListIntegrationRequestsParams struct {
	IntegrationID uuid.UUID   `json:"integration_id"`
	Limit         int32       `json:"limit"`
	Offset        int32       `json:"offset"`
	Ip            pgtype.Text `json:"ip"`
	StatusClass   pgtype.Int4 `json:"status_class"`
	Path          pgtype.Text `json:"path"`
	ErrorCode     pgtype.Text `json:"error_code"`
}

// A listagem de auditoria. `status_class` filtra por faixa (2, 4, 5) em vez de
// por código exato: quem investiga quer "os erros do cliente" ou "os nossos",
// não especificamente um 429.
func (q *Queries) ListIntegrationRequests(ctx context.Context, arg ListIntegrationRequestsParams) ([]IntegrationRequest, error) {
	rows, err := q.db.Query(ctx, listIntegrationRequests,
		arg.IntegrationID,
		arg.Limit,
		arg.Offset,
		arg.Ip,
		arg.StatusClass,
		arg.Path,
		arg.ErrorCode,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntegrationRequest{}
	for rows.Next() {
		var i IntegrationRequest
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.ApiKeyID,
			&i.Method,
			&i.Path,
			&i.StatusCode,
			&i.Ip,
			&i.UserAgent,
			&i.DurationMs,
			&i.ErrorCode,
			&i.DownloadID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationWebhooks = `-- name: ListIntegrationWebhooks :many
SELECT id, integration_id, url, secret, events, include_progress, active, last_delivery_at, last_status_code, last_error, consecutive_failures, disabled_reason, created_at, updated_at, deleted_at FROM integration_webhooks
WHERE integration_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListIntegrationWebhooks(ctx context.Context, integrationID uuid.UUID) ([]IntegrationWebhook, error) {
	rows, err := q.db.Query(ctx, listIntegrationWebhooks, integrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntegrationWebhook{}
	for rows.Next() {
		var i IntegrationWebhook
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.IncludeProgress,
			&i.Active,
			&i.LastDeliveryAt,
			&i.LastStatusCode,
			&i.LastError,
			&i.ConsecutiveFailures,
			&i.DisabledReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrations = `-- name: ListIntegrations :many
SELECT
  i.id, i.user_id, i.name, i.description, i.callback_base_url, i.daily_limit, i.max_file_size_bytes, i.rate_limit_per_minute, i.max_concurrent_downloads, i.allowed_ips, i.active, i.created_by, i.created_at, i.updated_at, i.deleted_at,
  u.email AS service_email,
  COUNT(d.id) FILTER (WHERE d.deleted_at IS NULL)::bigint AS downloads_total,
  COUNT(d.id) FILTER (
    WHERE d.deleted_at IS NULL
      AND d.created_at >= TIMEZONE('UTC', TIMEZONE('America/Sao_Paulo', CURRENT_DATE))
      AND d.created_at <  TIMEZONE('UTC', TIMEZONE('America/Sao_Paulo', CURRENT_DATE + INTERVAL '1 day'))
  )::bigint AS downloads_today,
  COUNT(d.id) FILTER (
    WHERE d.deleted_at IS NULL AND d.status IN ('PENDING', 'PROCESSING', 'RETRYING')
  )::bigint AS downloads_active,
  COALESCE(SUM(d.file_size_bytes) FILTER (
    WHERE d.deleted_at IS NULL AND d.status = 'COMPLETED'
  ), 0)::bigint AS storage_bytes,
  (
    SELECT COUNT(*) FROM integration_api_keys k
    WHERE k.integration_id = i.id AND k.revoked_at IS NULL
  )::bigint AS active_keys,
  -- O cast explícito é necessário: sem ele o sqlc não consegue inferir o tipo
  -- da subconsulta e gera interface{}, que a camada de cima não sabe formatar.
  (
    SELECT MAX(k.last_used_at) FROM integration_api_keys k
    WHERE k.integration_id = i.id
  )::timestamptz AS last_used_at
FROM integrations i
JOIN users u ON u.id = i.user_id
LEFT JOIN downloads d ON d.user_id = i.user_id
WHERE i.deleted_at IS NULL
  AND (
    $3::text IS NULL
    OR lower(i.name) LIKE '%' || lower($3::text) || '%'
    OR lower(COALESCE(i.description, '')) LIKE '%' || lower($3::text) || '%'
  )
  AND ($4::boolean IS NULL OR i.active = $4::boolean)
GROUP BY i.id, u.email
ORDER BY i.created_at DESC
LIMIT $1 OFFSET $2
`

type ListIntegrationsParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Search pgtype.Text `json:"search"`
	Active pgtype.Bool `json:"active"`
}

type ListIntegrationsRow struct {
	ID                     uuid.UUID          `json:"id"`
	UserID                 uuid.UUID          `json:"user_id"`
	Name                   string             `json:"name"`
	Description            pgtype.Text        `json:"description"`
	CallbackBaseUrl        pgtype.Text        `json:"callback_base_url"`
	DailyLimit             int32              `json:"daily_limit"`
	MaxFileSizeBytes       int64              `json:"max_file_size_bytes"`
	RateLimitPerMinute     int32              `json:"rate_limit_per_minute"`
	MaxConcurrentDownloads int32              `json:"max_concurrent_downloads"`
	AllowedIps             []string           `json:"allowed_ips"`
	Active                 bool               `json:"active"`
	CreatedBy              pgtype.UUID        `json:"created_by"`
	CreatedAt              *time.Time         `json:"created_at"`
	UpdatedAt              *time.Time         `json:"updated_at"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	ServiceEmail           string             `json:"service_email"`
	DownloadsTotal         int64              `json:"downloads_total"`
	DownloadsToday         int64              `json:"downloads_today"`
	DownloadsActive        int64              `json:"downloads_active"`
	StorageBytes           int64              `json:"storage_bytes"`
	ActiveKeys             int64              `json:"active_keys"`
	LastUsedAt             *time.Time         `json:"last_used_at"`
}

// Listagem do painel. Os números vêm na mesma consulta porque a tela mostra
// todos eles juntos, e uma chamada por integração transformaria a abertura da
// página em N+1 idas ao banco.
//
// `downloads_today` usa o MESMO corte de dia do contador do usuário comum
// (meia-noite em São Paulo, convertida para UTC). Um corte em UTC faria a cota
// virar às 21h e o painel discordaria da API.
func (q *Queries) ListIntegrations(ctx context.Context, arg ListIntegrationsParams) ([]ListIntegrationsRow, error) {
	rows, err := q.db.Query(ctx, listIntegrations,
		arg.Limit,
		arg.Offset,
		arg.Search,
		arg.Active,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIntegrationsRow{}
	for rows.Next() {
		var i ListIntegrationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CallbackBaseUrl,
			&i.DailyLimit,
			&i.MaxFileSizeBytes,
			&i.RateLimitPerMinute,
			&i.MaxConcurrentDownloads,
			&i.AllowedIps,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ServiceEmail,
			&i.DownloadsTotal,
			&i.DownloadsToday,
			&i.DownloadsActive,
			&i.StorageBytes,
			&i.ActiveKeys,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT
  d.id, d.webhook_id, d.integration_id, d.event_type, d.download_id, d.payload, d.status, d.attempts, d.last_status_code, d.last_error, d.duration_ms, d.delivered_at, d.created_at,
  w.url AS webhook_url
FROM integration_webhook_deliveries d
JOIN integration_webhooks w ON w.id = d.webhook_id
WHERE d.integration_id = $1
  AND ($4::core.webhook_delivery_status IS NULL
       OR d.status = $4::core.webhook_delivery_status)
  AND ($5::text IS NULL OR d.event_type = $5::text)
  AND ($6::uuid IS NULL OR d.download_id = $6::uuid)
ORDER BY d.created_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhookDeliveriesParams struct {
	IntegrationID uuid.UUID                     `json:"integration_id"`
	Limit         int32                         `json:"limit"`
	Offset        int32                         `json:"offset"`
	Status        NullCoreWebhookDeliveryStatus `json:"status"`
	EventType     pgtype.Text                   `json:"event_type"`
	DownloadID    pgtype.UUID                   `json:"download_id"`
}

type ListWebhookDeliveriesRow struct {
	ID             uuid.UUID                 `json:"id"`
	WebhookID      uuid.UUID                 `json:"webhook_id"`
	IntegrationID  uuid.UUID                 `json:"integration_id"`
	EventType      string                    `json:"event_type"`
	DownloadID     pgtype.UUID               `json:"download_id"`
	Payload        []byte                    `json:"payload"`
	Status         CoreWebhookDeliveryStatus `json:"status"`
	Attempts       int32                     `json:"attempts"`
	LastStatusCode pgtype.Int4               `json:"last_status_code"`
	LastError      pgtype.Text               `json:"last_error"`
	DurationMs     int32                     `json:"duration_ms"`
	DeliveredAt    pgtype.Timestamptz        `json:"delivered_at"`
	CreatedAt      *time.Time                `json:"created_at"`
	WebhookUrl     string                    `json:"webhook_url"`
}

func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]ListWebhookDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries,
		arg.IntegrationID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.EventType,
		arg.DownloadID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWebhookDeliveriesRow{}
	for rows.Next() {
		var i ListWebhookDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.IntegrationID,
			&i.EventType,
			&i.DownloadID,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastStatusCode,
			&i.LastError,
			&i.DurationMs,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.WebhookUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookDelivered = `-- name: MarkWebhookDelivered :exec
UPDATE integration_webhooks
SET last_delivery_at = now(),
    last_status_code = $2,
    last_error = NULL,
    consecutive_failures = 0,
    updated_at = now()
WHERE id = $1
`

type MarkWebhookDeliveredParams struct {
	ID             uuid.UUID   `json:"id"`
	LastStatusCode pgtype.Int4 `json:"last_status_code"`
}

func (q *Queries) MarkWebhookDelivered(ctx context.Context, arg MarkWebhookDeliveredParams) error {
	_, err := q.db.Exec(ctx, markWebhookDelivered, arg.ID, arg.LastStatusCode)
	return err
}

const markWebhookFailed = `-- name: MarkWebhookFailed :one
UPDATE integration_webhooks
SET last_delivery_at = now(),
    last_status_code = $2,
    last_error = $3,
    consecutive_failures = consecutive_failures + 1,
    updated_at = now()
WHERE id = $1
RETURNING id, integration_id, url, secret, events, include_progress, active, last_delivery_at, last_status_code, last_error, consecutive_failures, disabled_reason, created_at, updated_at, deleted_at
`

type MarkWebhookFailedParams struct {
	ID         uuid.UUID   `json:"id"`
	StatusCode pgtype.Int4 `json:"status_code"`
	Error      pgtype.Text `json:"error"`
}

// O contador de falhas consecutivas é o que permite desligar sozinho um
// endpoint que morreu: sem ele, um destino que responde 500 para sempre
// receberia reentrega eternamente.
func (q *Queries) MarkWebhookFailed(ctx context.Context, arg MarkWebhookFailedParams) (IntegrationWebhook, error) {
	row := q.db.QueryRow(ctx, markWebhookFailed, arg.ID, arg.StatusCode, arg.Error)
	var i IntegrationWebhook
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.IncludeProgress,
		&i.Active,
		&i.LastDeliveryAt,
		&i.LastStatusCode,
		&i.LastError,
		&i.ConsecutiveFailures,
		&i.DisabledReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const pruneIntegrationRequests = `-- name: PruneIntegrationRequests :execrows

DELETE FROM integration_requests
WHERE created_at < now() - ($1::int * INTERVAL '1 day')
`

// ---------------------------------------------------------------------------
// Retenção
// ---------------------------------------------------------------------------
// As duas tabelas de auditoria crescem a cada chamada e a cada notificação.
// Sem poda, a de requisições passa o histórico de downloads em volume e o
// painel fica lento por dado que ninguém mais vai olhar.
func (q *Queries) PruneIntegrationRequests(ctx context.Context, keepDays int32) (int64, error) {
	result, err := q.db.Exec(ctx, pruneIntegrationRequests, keepDays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneWebhookDeliveries = `-- name: PruneWebhookDeliveries :execrows
DELETE FROM integration_webhook_deliveries
WHERE (status = 'DELIVERED' AND created_at < now() - ($1::int * INTERVAL '1 day'))
   OR (status <> 'DELIVERED' AND created_at < now() - ($1::int * 3 * INTERVAL '1 day'))
`

// Entregas concluídas são podadas; as que falharam sobrevivem mais tempo,
// porque é justamente nelas que alguém vai procurar o motivo.
func (q *Queries) PruneWebhookDeliveries(ctx context.Context, keepDays int32) (int64, error) {
	result, err := q.db.Exec(ctx, pruneWebhookDeliveries, keepDays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeIntegrationAPIKey = `-- name: RevokeIntegrationAPIKey :one
UPDATE integration_api_keys
SET revoked_at = COALESCE(revoked_at, now()),
    revoked_reason = COALESCE(revoked_reason, $2)
WHERE id = $1
RETURNING id, integration_id, label, key_prefix, key_hash, last_four, revoked_at, revoked_reason, expires_at, last_used_at, last_used_ip, created_by, created_at
`

type RevokeIntegrationAPIKeyParams struct {
	ID     uuid.UUID   `json:"id"`
	Reason pgtype.Text `json:"reason"`
}

// Revogar é idempotente e preserva o carimbo original: uma segunda revogação
// não deve reescrever a data em que a chave de fato saiu do ar.
func (q *Queries) RevokeIntegrationAPIKey(ctx context.Context, arg RevokeIntegrationAPIKeyParams) (IntegrationApiKey, error) {
	row := q.db.QueryRow(ctx, revokeIntegrationAPIKey, arg.ID, arg.Reason)
	var i IntegrationApiKey
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Label,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.LastFour,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const revokeOtherIntegrationAPIKeys = `-- name: RevokeOtherIntegrationAPIKeys :exec
UPDATE integration_api_keys
SET revoked_at = now(),
    revoked_reason = COALESCE(revoked_reason, $2)
WHERE integration_id = $1
  AND id <> $3
  AND revoked_at IS NULL
`

type RevokeOtherIntegrationAPIKeysParams struct {
	IntegrationID uuid.UUID   `json:"integration_id"`
	Reason        pgtype.Text `json:"reason"`
	KeepID        uuid.UUID   `json:"keep_id"`
}

// Usada ao regerar: a chave nova entra e todas as anteriores caem na mesma
// operação, porque "regerar" significa que o valor antigo não vale mais.
func (q *Queries) RevokeOtherIntegrationAPIKeys(ctx context.Context, arg RevokeOtherIntegrationAPIKeysParams) error {
	_, err := q.db.Exec(ctx, revokeOtherIntegrationAPIKeys, arg.IntegrationID, arg.Reason, arg.KeepID)
	return err
}

const softDeleteIntegration = `-- name: SoftDeleteIntegration :exec
UPDATE integrations
SET deleted_at = now(), active = false, updated_at = now()
WHERE id = $1
`

// Remoção lógica, como a de usuário: o histórico de downloads referencia a
// conta de serviço e responde pela contabilidade de armazenamento.
func (q *Queries) SoftDeleteIntegration(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteIntegration, id)
	return err
}

const softDeleteIntegrationWebhook = `-- name: SoftDeleteIntegrationWebhook :exec
UPDATE integration_webhooks
SET deleted_at = now(), active = false, updated_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteIntegrationWebhook(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteIntegrationWebhook, id)
	return err
}

const touchIntegrationAPIKey = `-- name: TouchIntegrationAPIKey :exec
UPDATE integration_api_keys
SET last_used_at = now(), last_used_ip = $2
WHERE id = $1
`

type TouchIntegrationAPIKeyParams struct {
	ID         uuid.UUID   `json:"id"`
	LastUsedIp pgtype.Text `json:"last_used_ip"`
}

// Gravado a cada uso. É o que responde "esta chave ainda é usada?" antes de
// revogar uma que parece esquecida.
func (q *Queries) TouchIntegrationAPIKey(ctx context.Context, arg TouchIntegrationAPIKeyParams) error {
	_, err := q.db.Exec(ctx, touchIntegrationAPIKey, arg.ID, arg.LastUsedIp)
	return err
}

const updateIntegration = `-- name: UpdateIntegration :one
UPDATE integrations
SET
  name = COALESCE($2, name),
  description = COALESCE($3, description),
  callback_base_url = COALESCE($4, callback_base_url),
  daily_limit = COALESCE($5, daily_limit),
  max_file_size_bytes = COALESCE($6, max_file_size_bytes),
  rate_limit_per_minute = COALESCE($7, rate_limit_per_minute),
  max_concurrent_downloads = COALESCE($8, max_concurrent_downloads),
  -- O array não usa COALESCE com o próprio valor: uma lista VAZIA é uma
  -- escolha legítima ("aceitar qualquer IP"), e COALESCE não sabe distinguir
  -- "não mandei" de "mandei vazio". O sentinela é o NULL do narg.
  allowed_ips = CASE
      WHEN $9::text[] IS NULL THEN allowed_ips
      ELSE $9::text[]
    END,
  active = COALESCE($10, active),
  updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, user_id, name, description, callback_base_url, daily_limit, max_file_size_bytes, rate_limit_per_minute, max_concurrent_downloads, allowed_ips, active, created_by, created_at, updated_at, deleted_at
`

type UpdateIntegrationParams struct {
	ID                     uuid.UUID   `json:"id"`
	Name                   pgtype.Text `json:"name"`
	Description            pgtype.Text `json:"description"`
	CallbackBaseUrl        pgtype.Text `json:"callback_base_url"`
	DailyLimit             pgtype.Int4 `json:"daily_limit"`
	MaxFileSizeBytes       pgtype.Int8 `json:"max_file_size_bytes"`
	RateLimitPerMinute     pgtype.Int4 `json:"rate_limit_per_minute"`
	MaxConcurrentDownloads pgtype.Int4 `json:"max_concurrent_downloads"`
	AllowedIps             []string    `json:"allowed_ips"`
	Active                 pgtype.Bool `json:"active"`
}

func (q *Queries) UpdateIntegration(ctx context.Context, arg UpdateIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, updateIntegration,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CallbackBaseUrl,
		arg.DailyLimit,
		arg.MaxFileSizeBytes,
		arg.RateLimitPerMinute,
		arg.MaxConcurrentDownloads,
		arg.AllowedIps,
		arg.Active,
	)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CallbackBaseUrl,
		&i.DailyLimit,
		&i.MaxFileSizeBytes,
		&i.RateLimitPerMinute,
		&i.MaxConcurrentDownloads,
		&i.AllowedIps,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateIntegrationWebhook = `-- name: UpdateIntegrationWebhook :one
UPDATE integration_webhooks
SET
  url = COALESCE($2, url),
  events = CASE
      WHEN $3::text[] IS NULL THEN events
      ELSE $3::text[]
    END,
  include_progress = COALESCE($4, include_progress),
  active = COALESCE($5, active),
  secret = COALESCE($6, secret),
  -- Reativar limpa o histórico de falhas. Sem isso, um webhook religado depois
  -- de o cliente consertar o endpoint já nasceria a uma falha do desligamento
  -- automático.
  consecutive_failures = CASE
      WHEN COALESCE($5, active) THEN 0
      ELSE consecutive_failures
    END,
  disabled_reason = CASE
      WHEN COALESCE($5, active) THEN NULL
      ELSE disabled_reason
    END,
  updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, integration_id, url, secret, events, include_progress, active, last_delivery_at, last_status_code, last_error, consecutive_failures, disabled_reason, created_at, updated_at, deleted_at
`

type UpdateIntegrationWebhookParams struct {
	ID              uuid.UUID   `json:"id"`
	Url             pgtype.Text `json:"url"`
	Events          []string    `json:"events"`
	IncludeProgress pgtype.Bool `json:"include_progress"`
	Active          pgtype.Bool `json:"active"`
	Secret          pgtype.Text `json:"secret"`
}

func (q *Queries) UpdateIntegrationWebhook(ctx context.Context, arg UpdateIntegrationWebhookParams) (IntegrationWebhook, error) {
	row := q.db.QueryRow(ctx, updateIntegrationWebhook,
		arg.ID,
		arg.Url,
		arg.Events,
		arg.IncludeProgress,
		arg.Active,
		arg.Secret,
	)
	var i IntegrationWebhook
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.IncludeProgress,
		&i.Active,
		&i.LastDeliveryAt,
		&i.LastStatusCode,
		&i.LastError,
		&i.ConsecutiveFailures,
		&i.DisabledReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateWebhookDeliveryResult = `-- name: UpdateWebhookDeliveryResult :exec
UPDATE integration_webhook_deliveries
SET status = $1::core.webhook_delivery_status,
    attempts = attempts + 1,
    last_status_code = $2,
    last_error = $3,
    duration_ms = $4,
    delivered_at = CASE
        WHEN $1::core.webhook_delivery_status = 'DELIVERED' THEN now()
        ELSE delivered_at
      END
WHERE id = $5
`

type UpdateWebhookDeliveryResultParams struct {
	Status     CoreWebhookDeliveryStatus `json:"status"`
	StatusCode pgtype.Int4               `json:"status_code"`
	Error      pgtype.Text               `json:"error"`
	DurationMs int32                     `json:"duration_ms"`
	ID         uuid.UUID                 `json:"id"`
}

// O cast explícito não é decoração: o mesmo parâmetro é usado como valor da
// coluna e dentro do CASE, e sem ele o Postgres deduz tipos diferentes para os
// dois usos e recusa a consulta com "inconsistent types deduced for parameter".
// O sintoma é cruel: a entrega acontece, o cliente recebe, e o registro dela
// nunca é atualizado — o painel mostra tudo como pendente para sempre.
func (q *Queries) UpdateWebhookDeliveryResult(ctx context.Context, arg UpdateWebhookDeliveryResultParams) error {
	_, err := q.db.Exec(ctx, updateWebhookDeliveryResult,
		arg.Status,
		arg.StatusCode,
		arg.Error,
		arg.DurationMs,
		arg.ID,
	)
	return err
}

const webhookDeliveryStats = `-- name: WebhookDeliveryStats :one
SELECT
  COUNT(*)::bigint AS total,
  COUNT(*) FILTER (WHERE status = 'DELIVERED')::bigint AS delivered,
  COUNT(*) FILTER (WHERE status = 'FAILED')::bigint AS failed,
  COUNT(*) FILTER (WHERE status = 'PENDING')::bigint AS pending,
  COALESCE(AVG(duration_ms) FILTER (WHERE status = 'DELIVERED'), 0)::int AS avg_duration_ms
FROM integration_webhook_deliveries
WHERE integration_id = $1
  AND created_at >= now() - ($2::int * INTERVAL '1 hour')
`

type WebhookDeliveryStatsParams struct {
	IntegrationID uuid.UUID `json:"integration_id"`
	WindowHours   int32     `json:"window_hours"`
}

type WebhookDeliveryStatsRow struct {
	Total         int64 `json:"total"`
	Delivered     int64 `json:"delivered"`
	Failed        int64 `json:"failed"`
	Pending       int64 `json:"pending"`
	AvgDurationMs int32 `json:"avg_duration_ms"`
}

// Números da aba de entregas, na janela que a tela pediu.
func (q *Queries) WebhookDeliveryStats(ctx context.Context, arg WebhookDeliveryStatsParams) (WebhookDeliveryStatsRow, error) {
	row := q.db.QueryRow(ctx, webhookDeliveryStats, arg.IntegrationID, arg.WindowHours)
	var i WebhookDeliveryStatsRow
	err := row.Scan(
		&i.Total,
		&i.Delivered,
		&i.Failed,
		&i.Pending,
		&i.AvgDurationMs,
	)
	return i, err
}
