// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: maintenance.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countDownloadsToday = `-- name: CountDownloadsToday :one
SELECT COUNT(*) FROM downloads WHERE user_id = $1
  AND created_at >= TIMEZONE('UTC', TIMEZONE('America/Sao_Paulo', CURRENT_DATE))
  AND created_at <  TIMEZONE('UTC', TIMEZONE('America/Sao_Paulo', CURRENT_DATE + INTERVAL '1 day'))
`

func (q *Queries) CountDownloadsToday(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDownloadsToday, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
