// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CoreDownloadStatus string

const (
	CoreDownloadStatusPENDING    CoreDownloadStatus = "PENDING"
	CoreDownloadStatusPROCESSING CoreDownloadStatus = "PROCESSING"
	CoreDownloadStatusCOMPLETED  CoreDownloadStatus = "COMPLETED"
	CoreDownloadStatusFAILED     CoreDownloadStatus = "FAILED"
	CoreDownloadStatusCANCELED   CoreDownloadStatus = "CANCELED"
	CoreDownloadStatusEXPIRED    CoreDownloadStatus = "EXPIRED"
	CoreDownloadStatusRETRYING   CoreDownloadStatus = "RETRYING"
)

func (e *CoreDownloadStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoreDownloadStatus(s)
	case string:
		*e = CoreDownloadStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CoreDownloadStatus: %T", src)
	}
	return nil
}

type NullCoreDownloadStatus struct {
	CoreDownloadStatus CoreDownloadStatus `json:"core_download_status"`
	Valid              bool               `json:"valid"` // Valid is true if CoreDownloadStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoreDownloadStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CoreDownloadStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoreDownloadStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoreDownloadStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoreDownloadStatus), nil
}

type CoreFormatType string

const (
	CoreFormatTypeMP3  CoreFormatType = "MP3"
	CoreFormatTypeM4A  CoreFormatType = "M4A"
	CoreFormatTypeMP4  CoreFormatType = "MP4"
	CoreFormatTypeWEBM CoreFormatType = "WEBM"
	CoreFormatTypeBEST CoreFormatType = "BEST"
	CoreFormatTypeFLAC CoreFormatType = "FLAC"
)

func (e *CoreFormatType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoreFormatType(s)
	case string:
		*e = CoreFormatType(s)
	default:
		return fmt.Errorf("unsupported scan type for CoreFormatType: %T", src)
	}
	return nil
}

type NullCoreFormatType struct {
	CoreFormatType CoreFormatType `json:"core_format_type"`
	Valid          bool           `json:"valid"` // Valid is true if CoreFormatType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoreFormatType) Scan(value interface{}) error {
	if value == nil {
		ns.CoreFormatType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoreFormatType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoreFormatType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoreFormatType), nil
}

type CorePlanType string

const (
	CorePlanTypeFree       CorePlanType = "free"
	CorePlanTypePremium    CorePlanType = "premium"
	CorePlanTypeEnterprise CorePlanType = "enterprise"
)

func (e *CorePlanType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CorePlanType(s)
	case string:
		*e = CorePlanType(s)
	default:
		return fmt.Errorf("unsupported scan type for CorePlanType: %T", src)
	}
	return nil
}

type NullCorePlanType struct {
	CorePlanType CorePlanType `json:"core_plan_type"`
	Valid        bool         `json:"valid"` // Valid is true if CorePlanType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCorePlanType) Scan(value interface{}) error {
	if value == nil {
		ns.CorePlanType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CorePlanType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCorePlanType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CorePlanType), nil
}

type Download struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	OriginalUrl     string             `json:"original_url"`
	Title           string             `json:"title"`
	Format          CoreFormatType     `json:"format"`
	Status          CoreDownloadStatus `json:"status"`
	ThumbnailUrl    pgtype.Text        `json:"thumbnail_url"`
	FileUrl         pgtype.Text        `json:"file_url"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	DurationSeconds pgtype.Int4        `json:"duration_seconds"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	CreatedAt       *time.Time         `json:"created_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID                uuid.UUID          `json:"id"`
	FullName          string             `json:"full_name"`
	PhotoUrl          pgtype.Text        `json:"photo_url"`
	Email             string             `json:"email"`
	HashedPassword    string             `json:"hashed_password"`
	PasswordChangedAt *time.Time         `json:"password_changed_at"`
	Active            bool               `json:"active"`
	Plan              CorePlanType       `json:"plan"`
	DailyLimit        int32              `json:"daily_limit"`
	LastLogin         pgtype.Timestamptz `json:"last_login"`
	IsVerified        bool               `json:"is_verified"`
	CreatedAt         *time.Time         `json:"created_at"`
	UpdatedAt         *time.Time         `json:"updated_at"`
}
