// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CoreDownloadStatus string

const (
	CoreDownloadStatusPENDING    CoreDownloadStatus = "PENDING"
	CoreDownloadStatusPROCESSING CoreDownloadStatus = "PROCESSING"
	CoreDownloadStatusCOMPLETED  CoreDownloadStatus = "COMPLETED"
	CoreDownloadStatusFAILED     CoreDownloadStatus = "FAILED"
	CoreDownloadStatusCANCELED   CoreDownloadStatus = "CANCELED"
	CoreDownloadStatusEXPIRED    CoreDownloadStatus = "EXPIRED"
	CoreDownloadStatusRETRYING   CoreDownloadStatus = "RETRYING"
)

func (e *CoreDownloadStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoreDownloadStatus(s)
	case string:
		*e = CoreDownloadStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CoreDownloadStatus: %T", src)
	}
	return nil
}

type NullCoreDownloadStatus struct {
	CoreDownloadStatus CoreDownloadStatus `json:"core_download_status"`
	Valid              bool               `json:"valid"` // Valid is true if CoreDownloadStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoreDownloadStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CoreDownloadStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoreDownloadStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoreDownloadStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoreDownloadStatus), nil
}

type CoreFormatType string

const (
	CoreFormatTypeMP3  CoreFormatType = "MP3"
	CoreFormatTypeM4A  CoreFormatType = "M4A"
	CoreFormatTypeMP4  CoreFormatType = "MP4"
	CoreFormatTypeWEBM CoreFormatType = "WEBM"
	CoreFormatTypeBEST CoreFormatType = "BEST"
	CoreFormatTypeFLAC CoreFormatType = "FLAC"
)

func (e *CoreFormatType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoreFormatType(s)
	case string:
		*e = CoreFormatType(s)
	default:
		return fmt.Errorf("unsupported scan type for CoreFormatType: %T", src)
	}
	return nil
}

type NullCoreFormatType struct {
	CoreFormatType CoreFormatType `json:"core_format_type"`
	Valid          bool           `json:"valid"` // Valid is true if CoreFormatType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoreFormatType) Scan(value interface{}) error {
	if value == nil {
		ns.CoreFormatType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoreFormatType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoreFormatType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoreFormatType), nil
}

type CorePlanType string

const (
	CorePlanTypeFree       CorePlanType = "free"
	CorePlanTypePremium    CorePlanType = "premium"
	CorePlanTypeEnterprise CorePlanType = "enterprise"
)

func (e *CorePlanType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CorePlanType(s)
	case string:
		*e = CorePlanType(s)
	default:
		return fmt.Errorf("unsupported scan type for CorePlanType: %T", src)
	}
	return nil
}

type NullCorePlanType struct {
	CorePlanType CorePlanType `json:"core_plan_type"`
	Valid        bool         `json:"valid"` // Valid is true if CorePlanType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCorePlanType) Scan(value interface{}) error {
	if value == nil {
		ns.CorePlanType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CorePlanType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCorePlanType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CorePlanType), nil
}

type CoreUserKind string

const (
	CoreUserKindHuman   CoreUserKind = "human"
	CoreUserKindService CoreUserKind = "service"
)

func (e *CoreUserKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoreUserKind(s)
	case string:
		*e = CoreUserKind(s)
	default:
		return fmt.Errorf("unsupported scan type for CoreUserKind: %T", src)
	}
	return nil
}

type NullCoreUserKind struct {
	CoreUserKind CoreUserKind `json:"core_user_kind"`
	Valid        bool         `json:"valid"` // Valid is true if CoreUserKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoreUserKind) Scan(value interface{}) error {
	if value == nil {
		ns.CoreUserKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoreUserKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoreUserKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoreUserKind), nil
}

type CoreUserRole string

const (
	CoreUserRoleUser       CoreUserRole = "user"
	CoreUserRoleAdmin      CoreUserRole = "admin"
	CoreUserRoleSuperAdmin CoreUserRole = "super_admin"
)

func (e *CoreUserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoreUserRole(s)
	case string:
		*e = CoreUserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for CoreUserRole: %T", src)
	}
	return nil
}

type NullCoreUserRole struct {
	CoreUserRole CoreUserRole `json:"core_user_role"`
	Valid        bool         `json:"valid"` // Valid is true if CoreUserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoreUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.CoreUserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoreUserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoreUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoreUserRole), nil
}

type CoreWebhookDeliveryStatus string

const (
	CoreWebhookDeliveryStatusPENDING   CoreWebhookDeliveryStatus = "PENDING"
	CoreWebhookDeliveryStatusDELIVERED CoreWebhookDeliveryStatus = "DELIVERED"
	CoreWebhookDeliveryStatusFAILED    CoreWebhookDeliveryStatus = "FAILED"
)

func (e *CoreWebhookDeliveryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoreWebhookDeliveryStatus(s)
	case string:
		*e = CoreWebhookDeliveryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CoreWebhookDeliveryStatus: %T", src)
	}
	return nil
}

type NullCoreWebhookDeliveryStatus struct {
	CoreWebhookDeliveryStatus CoreWebhookDeliveryStatus `json:"core_webhook_delivery_status"`
	Valid                     bool                      `json:"valid"` // Valid is true if CoreWebhookDeliveryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoreWebhookDeliveryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CoreWebhookDeliveryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoreWebhookDeliveryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoreWebhookDeliveryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoreWebhookDeliveryStatus), nil
}

type CoreYoutubeAccountStatus string

const (
	CoreYoutubeAccountStatusNOTCONFIGURED CoreYoutubeAccountStatus = "NOT_CONFIGURED"
	CoreYoutubeAccountStatusAWAITINGLOGIN CoreYoutubeAccountStatus = "AWAITING_LOGIN"
	CoreYoutubeAccountStatusAUTHENTICATED CoreYoutubeAccountStatus = "AUTHENTICATED"
	CoreYoutubeAccountStatusREQUIRESAUTH  CoreYoutubeAccountStatus = "REQUIRES_AUTH"
	CoreYoutubeAccountStatusDISABLED      CoreYoutubeAccountStatus = "DISABLED"
	CoreYoutubeAccountStatusERROR         CoreYoutubeAccountStatus = "ERROR"
)

func (e *CoreYoutubeAccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoreYoutubeAccountStatus(s)
	case string:
		*e = CoreYoutubeAccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CoreYoutubeAccountStatus: %T", src)
	}
	return nil
}

type NullCoreYoutubeAccountStatus struct {
	CoreYoutubeAccountStatus CoreYoutubeAccountStatus `json:"core_youtube_account_status"`
	Valid                    bool                     `json:"valid"` // Valid is true if CoreYoutubeAccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoreYoutubeAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CoreYoutubeAccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoreYoutubeAccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoreYoutubeAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoreYoutubeAccountStatus), nil
}

type Download struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	OriginalUrl     string             `json:"original_url"`
	Title           string             `json:"title"`
	Format          CoreFormatType     `json:"format"`
	Status          CoreDownloadStatus `json:"status"`
	ThumbnailUrl    pgtype.Text        `json:"thumbnail_url"`
	FileUrl         pgtype.Text        `json:"file_url"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	DurationSeconds pgtype.Int4        `json:"duration_seconds"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	CreatedAt       *time.Time         `json:"created_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	FileSizeBytes   int64              `json:"file_size_bytes"`
	Platform        string             `json:"platform"`
	Provider        pgtype.Text        `json:"provider"`
	FormatID        pgtype.Text        `json:"format_id"`
	QualityLabel    pgtype.Text        `json:"quality_label"`
	ProgressPercent pgtype.Numeric     `json:"progress_percent"`
	DownloadedBytes int64              `json:"downloaded_bytes"`
	TotalBytes      int64              `json:"total_bytes"`
	SpeedBps        int64              `json:"speed_bps"`
	EtaSeconds      int32              `json:"eta_seconds"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
	Uploader        pgtype.Text        `json:"uploader"`
	FormatHeight    int32              `json:"format_height"`
	ErrorDetail     pgtype.Text        `json:"error_detail"`
}

type Integration struct {
	ID                     uuid.UUID          `json:"id"`
	UserID                 uuid.UUID          `json:"user_id"`
	Name                   string             `json:"name"`
	Description            pgtype.Text        `json:"description"`
	CallbackBaseUrl        pgtype.Text        `json:"callback_base_url"`
	DailyLimit             int32              `json:"daily_limit"`
	MaxFileSizeBytes       int64              `json:"max_file_size_bytes"`
	RateLimitPerMinute     int32              `json:"rate_limit_per_minute"`
	MaxConcurrentDownloads int32              `json:"max_concurrent_downloads"`
	AllowedIps             []string           `json:"allowed_ips"`
	Active                 bool               `json:"active"`
	CreatedBy              pgtype.UUID        `json:"created_by"`
	CreatedAt              *time.Time         `json:"created_at"`
	UpdatedAt              *time.Time         `json:"updated_at"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
}

type IntegrationApiKey struct {
	ID            uuid.UUID          `json:"id"`
	IntegrationID uuid.UUID          `json:"integration_id"`
	Label         string             `json:"label"`
	KeyPrefix     string             `json:"key_prefix"`
	KeyHash       string             `json:"key_hash"`
	LastFour      string             `json:"last_four"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason pgtype.Text        `json:"revoked_reason"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt    pgtype.Timestamptz `json:"last_used_at"`
	LastUsedIp    pgtype.Text        `json:"last_used_ip"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CreatedAt     *time.Time         `json:"created_at"`
}

type IntegrationRequest struct {
	ID            int64       `json:"id"`
	IntegrationID uuid.UUID   `json:"integration_id"`
	ApiKeyID      pgtype.UUID `json:"api_key_id"`
	Method        string      `json:"method"`
	Path          string      `json:"path"`
	StatusCode    int32       `json:"status_code"`
	Ip            string      `json:"ip"`
	UserAgent     string      `json:"user_agent"`
	DurationMs    int32       `json:"duration_ms"`
	ErrorCode     pgtype.Text `json:"error_code"`
	DownloadID    pgtype.UUID `json:"download_id"`
	CreatedAt     *time.Time  `json:"created_at"`
}

type IntegrationWebhook struct {
	ID                  uuid.UUID          `json:"id"`
	IntegrationID       uuid.UUID          `json:"integration_id"`
	Url                 string             `json:"url"`
	Secret              string             `json:"secret"`
	Events              []string           `json:"events"`
	IncludeProgress     bool               `json:"include_progress"`
	Active              bool               `json:"active"`
	LastDeliveryAt      pgtype.Timestamptz `json:"last_delivery_at"`
	LastStatusCode      pgtype.Int4        `json:"last_status_code"`
	LastError           pgtype.Text        `json:"last_error"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	DisabledReason      pgtype.Text        `json:"disabled_reason"`
	CreatedAt           *time.Time         `json:"created_at"`
	UpdatedAt           *time.Time         `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
}

type IntegrationWebhookDelivery struct {
	ID             uuid.UUID                 `json:"id"`
	WebhookID      uuid.UUID                 `json:"webhook_id"`
	IntegrationID  uuid.UUID                 `json:"integration_id"`
	EventType      string                    `json:"event_type"`
	DownloadID     pgtype.UUID               `json:"download_id"`
	Payload        []byte                    `json:"payload"`
	Status         CoreWebhookDeliveryStatus `json:"status"`
	Attempts       int32                     `json:"attempts"`
	LastStatusCode pgtype.Int4               `json:"last_status_code"`
	LastError      pgtype.Text               `json:"last_error"`
	DurationMs     int32                     `json:"duration_ms"`
	DeliveredAt    pgtype.Timestamptz        `json:"delivered_at"`
	CreatedAt      *time.Time                `json:"created_at"`
}

type User struct {
	ID                uuid.UUID          `json:"id"`
	FullName          string             `json:"full_name"`
	PhotoUrl          pgtype.Text        `json:"photo_url"`
	Email             string             `json:"email"`
	HashedPassword    string             `json:"hashed_password"`
	PasswordChangedAt *time.Time         `json:"password_changed_at"`
	Active            bool               `json:"active"`
	Plan              CorePlanType       `json:"plan"`
	DailyLimit        int32              `json:"daily_limit"`
	LastLogin         pgtype.Timestamptz `json:"last_login"`
	IsVerified        bool               `json:"is_verified"`
	CreatedAt         *time.Time         `json:"created_at"`
	UpdatedAt         *time.Time         `json:"updated_at"`
	Role              CoreUserRole       `json:"role"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	Kind              CoreUserKind       `json:"kind"`
}

type YoutubeAccount struct {
	ID                  uuid.UUID                `json:"id"`
	Label               string                   `json:"label"`
	Email               pgtype.Text              `json:"email"`
	Status              CoreYoutubeAccountStatus `json:"status"`
	ProfileDir          string                   `json:"profile_dir"`
	Active              bool                     `json:"active"`
	Priority            int32                    `json:"priority"`
	LastCheckedAt       pgtype.Timestamptz       `json:"last_checked_at"`
	LastAuthenticatedAt pgtype.Timestamptz       `json:"last_authenticated_at"`
	LastUsedAt          pgtype.Timestamptz       `json:"last_used_at"`
	LastError           pgtype.Text              `json:"last_error"`
	CreatedBy           pgtype.UUID              `json:"created_by"`
	CreatedAt           *time.Time               `json:"created_at"`
	UpdatedAt           *time.Time               `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz       `json:"deleted_at"`
	Platform            string                   `json:"platform"`
}
