// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: youtube_accounts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimYoutubeAccount = `-- name: ClaimYoutubeAccount :one
UPDATE youtube_accounts
SET last_used_at = now(), updated_at = now()
WHERE id = (
  SELECT id FROM youtube_accounts
  WHERE deleted_at IS NULL
    AND active = true
    AND status = 'AUTHENTICATED'
    AND NOT (id = ANY($1::uuid[]))
  ORDER BY priority ASC, last_used_at ASC NULLS FIRST, created_at ASC
  LIMIT 1
  FOR UPDATE SKIP LOCKED
)
RETURNING id, label, email, status, profile_dir, active, priority, last_checked_at, last_authenticated_at, last_used_at, last_error, created_by, created_at, updated_at, deleted_at
`

// Reivindica a conta autenticada usada há mais tempo e já registra o uso na
// mesma operação, de modo que o rodízio não dependa de um UPDATE posterior.
//
// FOR UPDATE SKIP LOCKED faz dois workers simultâneos pegarem contas
// diferentes em vez de disputarem a mesma linha. O parâmetro exclude carrega
// as contas já descartadas nesta tentativa, o que permite passar para a
// próxima quando uma sessão se revela inválida.
//
// Não é rotação para contornar limites do YouTube: é distribuição justa entre
// as contas legítimas do próprio administrador, respeitando a prioridade.
func (q *Queries) ClaimYoutubeAccount(ctx context.Context, exclude []uuid.UUID) (YoutubeAccount, error) {
	row := q.db.QueryRow(ctx, claimYoutubeAccount, exclude)
	var i YoutubeAccount
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Email,
		&i.Status,
		&i.ProfileDir,
		&i.Active,
		&i.Priority,
		&i.LastCheckedAt,
		&i.LastAuthenticatedAt,
		&i.LastUsedAt,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countAuthenticatedYoutubeAccounts = `-- name: CountAuthenticatedYoutubeAccounts :one
SELECT COUNT(*) FROM youtube_accounts
WHERE deleted_at IS NULL
  AND active = true
  AND status = 'AUTHENTICATED'
`

func (q *Queries) CountAuthenticatedYoutubeAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuthenticatedYoutubeAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countYoutubeAccounts = `-- name: CountYoutubeAccounts :one
SELECT COUNT(*) FROM youtube_accounts
WHERE deleted_at IS NULL
`

func (q *Queries) CountYoutubeAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countYoutubeAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createYoutubeAccount = `-- name: CreateYoutubeAccount :one
INSERT INTO youtube_accounts (
  id, label, email, status, profile_dir, priority, created_by
)
VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, label, email, status, profile_dir, active, priority, last_checked_at, last_authenticated_at, last_used_at, last_error, created_by, created_at, updated_at, deleted_at
`

type CreateYoutubeAccountParams struct {
	ID         uuid.UUID                `json:"id"`
	Label      string                   `json:"label"`
	Email      pgtype.Text              `json:"email"`
	Status     CoreYoutubeAccountStatus `json:"status"`
	ProfileDir string                   `json:"profile_dir"`
	Priority   int32                    `json:"priority"`
	CreatedBy  pgtype.UUID              `json:"created_by"`
}

func (q *Queries) CreateYoutubeAccount(ctx context.Context, arg CreateYoutubeAccountParams) (YoutubeAccount, error) {
	row := q.db.QueryRow(ctx, createYoutubeAccount,
		arg.ID,
		arg.Label,
		arg.Email,
		arg.Status,
		arg.ProfileDir,
		arg.Priority,
		arg.CreatedBy,
	)
	var i YoutubeAccount
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Email,
		&i.Status,
		&i.ProfileDir,
		&i.Active,
		&i.Priority,
		&i.LastCheckedAt,
		&i.LastAuthenticatedAt,
		&i.LastUsedAt,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteYoutubeAccount = `-- name: DeleteYoutubeAccount :exec
UPDATE youtube_accounts
SET deleted_at = now(), active = false, status = 'DISABLED', updated_at = now()
WHERE id = $1
`

func (q *Queries) DeleteYoutubeAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteYoutubeAccount, id)
	return err
}

const getYoutubeAccountByID = `-- name: GetYoutubeAccountByID :one
SELECT id, label, email, status, profile_dir, active, priority, last_checked_at, last_authenticated_at, last_used_at, last_error, created_by, created_at, updated_at, deleted_at FROM youtube_accounts
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetYoutubeAccountByID(ctx context.Context, id uuid.UUID) (YoutubeAccount, error) {
	row := q.db.QueryRow(ctx, getYoutubeAccountByID, id)
	var i YoutubeAccount
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Email,
		&i.Status,
		&i.ProfileDir,
		&i.Active,
		&i.Priority,
		&i.LastCheckedAt,
		&i.LastAuthenticatedAt,
		&i.LastUsedAt,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getYoutubeAccounts = `-- name: GetYoutubeAccounts :many
SELECT id, label, email, status, profile_dir, active, priority, last_checked_at, last_authenticated_at, last_used_at, last_error, created_by, created_at, updated_at, deleted_at FROM youtube_accounts
WHERE deleted_at IS NULL
ORDER BY priority ASC, created_at ASC
`

func (q *Queries) GetYoutubeAccounts(ctx context.Context) ([]YoutubeAccount, error) {
	rows, err := q.db.Query(ctx, getYoutubeAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []YoutubeAccount{}
	for rows.Next() {
		var i YoutubeAccount
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Email,
			&i.Status,
			&i.ProfileDir,
			&i.Active,
			&i.Priority,
			&i.LastCheckedAt,
			&i.LastAuthenticatedAt,
			&i.LastUsedAt,
			&i.LastError,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYoutubeAccountsForHealthCheck = `-- name: GetYoutubeAccountsForHealthCheck :many
SELECT id, label, email, status, profile_dir, active, priority, last_checked_at, last_authenticated_at, last_used_at, last_error, created_by, created_at, updated_at, deleted_at FROM youtube_accounts
WHERE deleted_at IS NULL
  AND active = true
  AND status IN ('AUTHENTICATED', 'REQUIRES_AUTH', 'AWAITING_LOGIN', 'ERROR')
ORDER BY last_checked_at ASC NULLS FIRST
`

func (q *Queries) GetYoutubeAccountsForHealthCheck(ctx context.Context) ([]YoutubeAccount, error) {
	rows, err := q.db.Query(ctx, getYoutubeAccountsForHealthCheck)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []YoutubeAccount{}
	for rows.Next() {
		var i YoutubeAccount
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Email,
			&i.Status,
			&i.ProfileDir,
			&i.Active,
			&i.Priority,
			&i.LastCheckedAt,
			&i.LastAuthenticatedAt,
			&i.LastUsedAt,
			&i.LastError,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateYoutubeAccount = `-- name: UpdateYoutubeAccount :one
UPDATE youtube_accounts
SET
  label = COALESCE($2, label),
  email = COALESCE($3, email),
  status = COALESCE($4, status),
  active = COALESCE($5, active),
  priority = COALESCE($6, priority),
  updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, label, email, status, profile_dir, active, priority, last_checked_at, last_authenticated_at, last_used_at, last_error, created_by, created_at, updated_at, deleted_at
`

type UpdateYoutubeAccountParams struct {
	ID       uuid.UUID                    `json:"id"`
	Label    pgtype.Text                  `json:"label"`
	Email    pgtype.Text                  `json:"email"`
	Status   NullCoreYoutubeAccountStatus `json:"status"`
	Active   pgtype.Bool                  `json:"active"`
	Priority pgtype.Int4                  `json:"priority"`
}

func (q *Queries) UpdateYoutubeAccount(ctx context.Context, arg UpdateYoutubeAccountParams) (YoutubeAccount, error) {
	row := q.db.QueryRow(ctx, updateYoutubeAccount,
		arg.ID,
		arg.Label,
		arg.Email,
		arg.Status,
		arg.Active,
		arg.Priority,
	)
	var i YoutubeAccount
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Email,
		&i.Status,
		&i.ProfileDir,
		&i.Active,
		&i.Priority,
		&i.LastCheckedAt,
		&i.LastAuthenticatedAt,
		&i.LastUsedAt,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateYoutubeAccountStatus = `-- name: UpdateYoutubeAccountStatus :one
UPDATE youtube_accounts
SET
  status = $1,
  last_error = $2,
  last_checked_at = now(),
  last_authenticated_at = CASE
    WHEN $1::core.youtube_account_status = 'AUTHENTICATED' THEN now()
    ELSE last_authenticated_at
  END,
  updated_at = now()
WHERE id = $3
  AND deleted_at IS NULL
RETURNING id, label, email, status, profile_dir, active, priority, last_checked_at, last_authenticated_at, last_used_at, last_error, created_by, created_at, updated_at, deleted_at
`

type UpdateYoutubeAccountStatusParams struct {
	Status    CoreYoutubeAccountStatus `json:"status"`
	LastError pgtype.Text              `json:"last_error"`
	ID        uuid.UUID                `json:"id"`
}

// O cast explícito é necessário: sem ele o Postgres deduz tipos diferentes para
// o mesmo parâmetro, usado como valor da coluna e dentro do CASE.
func (q *Queries) UpdateYoutubeAccountStatus(ctx context.Context, arg UpdateYoutubeAccountStatusParams) (YoutubeAccount, error) {
	row := q.db.QueryRow(ctx, updateYoutubeAccountStatus, arg.Status, arg.LastError, arg.ID)
	var i YoutubeAccount
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Email,
		&i.Status,
		&i.ProfileDir,
		&i.Active,
		&i.Priority,
		&i.LastCheckedAt,
		&i.LastAuthenticatedAt,
		&i.LastUsedAt,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
