name: Build and Deploy Worker Docker Image

on:
  push:
    tags:
      - "api/v*.*.*"

jobs:
  build-and-push:
    name: Build, Tag & Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version tag
        id: extract_tag
        run: |
          # GITHUB_REF_NAME já vem como 'api/v.*.*'
          TAG_NAME="${GITHUB_REF_NAME#api/}"
          echo "VERSION=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "Extracted version: $TAG_NAME"

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./api
          file: ./api/Dockerfile.worker
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/advideo-worker:latest
            ghcr.io/${{ github.repository_owner }}/advideo-worker:${{ steps.extract_tag.outputs.VERSION }}
